export const TYPES = {
	RECEIVE_REGISTERED_CHANNELS_SUCCESS:
		'RECEIVE_REGISTERED_CHANNELS_SUCCESS' as const,
	RECEIVE_REGISTERED_CHANNELS_ERROR:
		'RECEIVE_REGISTERED_CHANNELS_ERROR' as const,
	RECEIVE_RECOMMENDED_CHANNELS_SUCCESS:
		'RECEIVE_RECOMMENDED_CHANNELS_SUCCESS' as const,
	RECEIVE_RECOMMENDED_CHANNELS_ERROR:
		'RECEIVE_RECOMMENDED_CHANNELS_ERROR' as const,
	RECEIVE_CAMPAIGNS: 'RECEIVE_CAMPAIGNS' as const,
	RECEIVE_CAMPAIGN_TYPES: 'RECEIVE_CAMPAIGN_TYPES' as const,
};
