<?php
/**
 * Chilean provinces
 *
 * @package WooCommerce/i18n
 * @version 2.4.0
 * Created: KatuSoftware.cl
 */
global $states;
defined( 'ABSPATH' ) || exit;
$states['CL'] = array(
	'A' => __( 'Arica y Parinacota', 'woocommerce' ),
	'T' => __( 'Tarapac&aacute', 'woocommerce' ),
	'N' => __( 'Antofagasta', 'woocommerce' ),
	'C' => __( 'Atacama', 'woocommerce' ),
	'O' => __( 'Coquimbo', 'woocommerce' ),
	'V' => __( 'Valpara&iacuteso', 'woocommerce' ),
	'L' => __( 'Libertador General Bernardo O&#8217Higgins', 'woocommerce' ),
	'E' => __( 'Entre R&iacute;os', 'woocommerce' ),
	'M' => __( 'Maule', 'woocommerce' ),
	'B' => __( 'B&iacuteso B&iacuteso', 'woocommerce' ),
	'R' => __( 'Araucan&iacutesa', 'woocommerce' ),
	'S' => __( 'Los R&iacutesos', 'woocommerce' ),
	'G' => __( 'Los Lagos', 'woocommerce' ),
	'I' => __( 'Ais&eacuten', 'woocommerce' ),
	'Y' => __( 'Magallanes y la Ant&aacutertica Chilena', 'woocommerce' ),
	'P' => __( 'Metropolitana', 'woocommerce' ),
);
