packages:
    - 'packages/js/*'
    - 'plugins/*'
    - 'plugins/woocommerce/client/legacy'
    - 'tools/monorepo-merge'
    - 'tools/code-analyzer'
    - 'tools/create-extension'
    - 'tools/package-release'
    - 'tools/cherry-pick'
    - 'tools/release-posts'
    - 'tools/cli-core'
    - 'tools/version-bump'
    - 'tools/storybook'
    - 'tools/monorepo-utils'
