<?php

declare( strict_types = 1 );

namespace Automattic\WooCommerce\Admin\API\AI;

use Automattic\WooCommerce\Blocks\AI\Connection;
use Automattic\WooCommerce\Blocks\AIContent\UpdateProducts;
use WP_Error;
use WP_REST_Request;
use WP_REST_Response;

defined( 'ABSPATH' ) || exit;

/**
 * Product controller
 *
 * @internal
 */
class Products extends AIEndpoint {
	/**
	 * Endpoint.
	 *
	 * @var string
	 */
	protected $endpoint = 'products';

	/**
	 * Register routes.
	 */
	public function register_routes() {
		$this->register(
			array(
				array(
					'methods'             => \WP_REST_Server::CREATABLE,
					'callback'            => array( $this, 'generate_products_content' ),
					'permission_callback' => array( Middleware::class, 'is_authorized' ),
					'args'                => array(
						'business_description' => array(
							'description' => __( 'The business description for a given store.', 'woocommerce' ),
							'type'        => 'string',
						),
						'images'               => array(
							'description' => __( 'The images for a given store.', 'woocommerce' ),
							'type'        => 'object',
						),
					),
				),
				array(
					'methods'             => \WP_REST_Server::DELETABLE,
					'callback'            => array( $this, 'delete_products' ),
					'permission_callback' => array( Middleware::class, 'is_authorized' ),
				),
			)
		);
	}

	/**
	 * Generate the content for the products.
	 *
	 * @param  WP_REST_Request $request Request object.
	 *
	 * @return WP_Error|WP_REST_Response
	 */
	public function generate_products_content( WP_REST_Request $request ) {
		$allow_ai_connection = get_option( 'woocommerce_blocks_allow_ai_connection' );

		if ( ! $allow_ai_connection ) {
			return rest_ensure_response(
				new WP_Error(
					'ai_connection_not_allowed',
					__( 'AI content generation is not allowed on this store. Update your store settings if you wish to enable this feature.', 'woocommerce' )
				)
			);
		}

		$business_description = sanitize_text_field( wp_unslash( $request['business_description'] ) );

		if ( empty( $business_description ) ) {
			$business_description = get_option( 'woo_ai_describe_store_description' );
		}

		$ai_connection = new Connection();

		$site_id = $ai_connection->get_site_id();

		if ( is_wp_error( $site_id ) ) {
			return $site_id;
		}

		$token = $ai_connection->get_jwt_token( $site_id );

		if ( is_wp_error( $token ) ) {
			return $token;
		}

		$images = $request['images'];

		$populate_products = ( new UpdateProducts() )->generate_content( $ai_connection, $token, $images, $business_description );

		if ( is_wp_error( $populate_products ) ) {
			return $populate_products;
		}

		if ( ! isset( $populate_products['product_content'] ) ) {
			return new WP_Error( 'product_content_not_found', __( 'Product content not found.', 'woocommerce' ) );
		}

		$product_content = $populate_products['product_content'];

		$item = array(
			'ai_content_generated' => true,
			'product_content'      => $product_content,
		);

		return rest_ensure_response( $item );
	}

	/**
	 * Remove products generated by AI.
	 *
	 * @return WP_Error|WP_REST_Response
	 */
	public function delete_products() {
		( new UpdateProducts() )->reset_products_content();
		return rest_ensure_response( array( 'removed' => true ) );
	}
}
