<?php
declare( strict_types = 1 );

namespace Automattic\WooCommerce\Internal\Blocks;

use Automattic\WooCommerce\Blocks\Domain\Package;

/**
 * Loads assets and block registrations generated by the block-library wp-build package.
 *
 * @since 11.0.0
 */
class BlockLibraryRegistry {

	/**
	 * Path for generated block-library build output.
	 */
	private const BUILD_PATH = 'assets/client/blocks/';

	/**
	 * Package instance.
	 *
	 * @var Package
	 */
	private Package $package;

	/**
	 * Constructor.
	 *
	 * @param Package $package Package instance.
	 */
	public function __construct( Package $package ) {
		$this->package = $package;
	}

	/**
	 * Initialize block-library asset and block registration.
	 *
	 * @internal
	 */
	final public function init(): void {
		$this->load_asset_registration();
		$this->register_block_metadata_collection();
		$this->load_block_registration();
	}

	/**
	 * Load generated asset registration.
	 */
	public function load_asset_registration(): void {
		$build_file = $this->package->get_path( self::BUILD_PATH . 'build.php' );
		if ( ! file_exists( $build_file ) ) {
			return;
		}

		require_once $build_file;
	}

	/**
	 * Register the generated block metadata collection.
	 */
	public function register_block_metadata_collection(): void {
		$blocks_path    = $this->package->get_path( self::BUILD_PATH );
		$meta_file_path = $this->package->get_path( self::BUILD_PATH . 'blocks-json.php' );

		if ( ! function_exists( 'wp_register_block_metadata_collection' ) || ! file_exists( $meta_file_path ) ) {
			return;
		}

		add_filter( 'doing_it_wrong_trigger_error', array( __CLASS__, 'bypass_block_metadata_doing_it_wrong' ), 10, 4 );
		wp_register_block_metadata_collection(
			$blocks_path,
			$meta_file_path
		);
		remove_filter( 'doing_it_wrong_trigger_error', array( __CLASS__, 'bypass_block_metadata_doing_it_wrong' ), 10 );
	}

	/**
	 * Load generated PHP files for blocks that register themselves.
	 */
	public function load_block_registration(): void {
		$block_files = glob( $this->package->get_path( self::BUILD_PATH . '*/index.php' ) );

		if ( false === $block_files ) {
			return;
		}

		foreach ( $block_files as $block_file ) {
			if ( $this->is_self_registering_block_file( $block_file ) ) {
				require_once $block_file;
			}
		}
	}

	/**
	 * Check whether a block PHP file registers its block type directly.
	 *
	 * @param string $block_file Path to the block PHP file.
	 * @return bool True when the block PHP file should be loaded.
	 */
	private function is_self_registering_block_file( string $block_file ): bool {
		$metadata = wp_json_file_decode(
			dirname( $block_file ) . '/block.json',
			array(
				'associative' => true,
			)
		);

		return is_array( $metadata ) && ! isset( $metadata['render'] );
	}

	/**
	 * Temporarily bypass _doing_it_wrong() notices for block metadata collection registration.
	 *
	 * @param bool   $trigger  Whether to trigger the error.
	 * @param string $function_name The function that was called.
	 * @param string $message The message explaining what was done incorrectly.
	 * @param string $version The version of WordPress where the message was added.
	 * @return bool Whether to trigger the error.
	 */
	public static function bypass_block_metadata_doing_it_wrong( bool $trigger, string $function_name, string $message, string $version ): bool {
		unset( $message, $version );

		if ( 'WP_Block_Metadata_Registry::register_collection' === $function_name ) {
			return false;
		}

		return $trigger;
	}
}
