let config = require( '../../playwright.config.js' );
const { devices } = require( '@playwright/test' );

config = {
	...config,
	projects: [
		{
			name: 'default pressable',
			use: { ...devices[ 'Desktop Chrome' ] },
			testMatch: [
				'**/basic.spec.js',
				'**/activate-and-setup/**/*.spec.js',
				'**/admin-analytics/**/*.spec.js',
				'**/admin-marketing/**/*.spec.js',
				'**/admin-tasks/**/*.spec.js',
				'**/customize-store/**/*.spec.js',
				'**/merchant/**/*.spec.js',
				'**/shopper/account-email-receiving.spec.js',
				'**/shopper/add-to-cart.spec.js',
				'**/shopper/cart-block-calculate-shipping.spec.js',
				'**/shopper/cart-block-coupons.spec.js',
				'**/shopper/cart-block.spec.js',
				'**/shopper/cart-calculate-shipping.spec.js',
				'**/shopper/cart-checkout-block-calculate-tax.spec.js',
				'**/shopper/cart-checkout-calculate-tax.spec.js',
				'**/shopper/cart-checkout-coupons.spec.js',
				'**/shopper/cart-checkout-restricted-coupons.spec.js',
				'**/shopper/cart-redirection.spec.js',
				'**/shopper/cart.spec.js',
				'**/shopper/checkout-block-coupons.spec.js',
				'**/shopper/checkout-block.spec.js',
				'**/shopper/checkout-create-account.spec.js',
				'**/shopper/checkout-login.spec.js',
				'**/shopper/checkout.spec.js',
				'**/shopper/dashboard-access.spec.js',
				'**/shopper/mini-cart.spec.js',
				'**/shopper/my-account-addresses.spec.js',
				'**/shopper/my-account-create-account.spec.js',
				'**/shopper/my-account-downloads.spec.js',
				'**/shopper/my-account-pay-order.spec.js',
				'**/shopper/my-account.spec.js',
				'**/shopper/order-email-receiving.spec.js',
				'**/shopper/product-grouped.spec.js',
				'**/shopper/product-simple.spec.js',
				'**/shopper/product-tags-attributes.spec.js',
				'**/shopper/product-variable.spec.js',
				'**/shopper/shop-search-browse-sort.spec.js',
				'**/shopper/shop-title-after-deletion.spec.js',
			],
			grepInvert: /@skip-on-default-pressable/,
		},
	],
};

module.exports = config;
