<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries;

use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Inheritance\OverriddenCapQuery as OverriddenCapQueryCommand;
use Automattic\WooCommerce\Internal\Api\QueryInfoExtractor;
use Automattic\WooCommerce\Internal\Api\Utils;
use Automattic\WooCommerce\Internal\Api\Schema\ResolveInfo;
use Automattic\WooCommerce\Internal\Api\Schema\Type;

class OverriddenCapQuery {
	public static function get_field_definition(): array {
		return array(
			'type' => Type::nonNull(new \Automattic\WooCommerce\Internal\Api\Schema\ObjectType(array(
				'name' => 'OverriddenCapQueryResult',
				'fields' => array(
					'result' => array( 'type' => Type::nonNull(Type::string()) ),
				),
			))),
			'description' => __( 'Overrides the inherited manage_options with manage_categories', 'woocommerce' ),
			'args' => array(
			),
			'resolve' => array( self::class, 'resolve' ),
		);
	}

	public static function resolve( mixed $root, array $args, mixed $context, ResolveInfo $info ): mixed {
		Utils::check_current_user_can( 'manage_categories' );

		$command = \Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Container::get( OverriddenCapQueryCommand::class );

		$execute_args = array();

		$result = Utils::execute_command( $command, $execute_args );

		return array( 'result' => $result );
	}
}
