name: Enforce read-only repo status

on:
    issues:
        types: opened
    pull_request_target:
        types: opened

permissions:
    # dessant/repo-lockdown
    issues: write
    pull-requests: write

jobs:
    lockdown:
        runs-on: ubuntu-latest
        steps:
            - uses: dessant/repo-lockdown@v5
              with:
                  github-token: ${{ github.token }}
                  issue-comment: |
                      Thank you for your interest!

                      Issues should be filed at https://github.com/woocommerce/woocommerce/issues. Be sure to mention the `woocommerce-analytics` package.
                  skip-closed-issue-comment: true
                  pr-comment: |
                      Thank you for your interest!

                      Pull requests should be made against the monorepo at https://github.com/woocommerce/woocommerce.
                  skip-closed-pr-comment: true
