name: 'WooCommerce: release checklist'
description: Create a new issue to track the next WooCommerce core release progress.
title: "WooCommerce RELEASE_VERSION: RC, final and dot-releases progress tracking"
body:
  - type: markdown
    attributes:
      value: |
        This issue provides visibility on the progress of the release process of WooCommerce core RELEASE_VERSION and 
        centralizes any conversations about it. The ultimate goal of this issue is to keep a reference of the steps, 
        resources, work, and conversations about this release so it can be helpful for the next contributors releasing 
        a new WooCommerce core version.

        -   WooCommerce core version to release: RELEASE_VERSION ([milestone](https://github.com/woocommerce/woocommerce/milestone/MILESTONE_ID))
        -   Release lead: RELEASE_LEAD
        -   RC release date: RELEASE_DATE
        -   Final release date: RELEASE_DATE
        -   WooCommerce core change log: [here](https://github.com/woocommerce/woocommerce/blob/trunk/changelog.txt)

  - type: markdown
    attributes:
      value: |
        ## Resources

        -   [Release calendar](https://developer.woocommerce.com/release-calendar/)
        -   [Previous releases](https://developer.woocommerce.com/releases/)
        -   Latest (version 9.9+) [release process changes](https://developer.woocommerce.com/2025/03/05/upcoming-changes-to-the-woocommerce-release-process/)
        -   Internal detailed reference to the release process: Pf59Ax-7F-p2

  - type: markdown
    attributes:
      value: |
        ## Checklist

  - type: markdown
    attributes:
      value: |
        ### RC release
        
        #### Get release artifact ready

        -    [] Ensure minimally required WordPress and PHP versions are up-to-date
        -    [] Ensure all [CFEs](https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22code%20freeze%20exception%22) for the target release version are addressed and merged
        -    [] Validate stable tag in `readme.txt` for the release branch and update if necessary
        -    [] Validate stable tag in `readme.txt` for the SVN `trunk` ([here](https://plugins.svn.wordpress.org/woocommerce/trunk/readme.txt))
        -    [] Skip changelog generation (?)
        -    [] Create a PR to bump version in source code with `GITHUB_TOKEN=<your_PAT_token> pnpm utils code-freeze version-bump -b release/9.9 9.9.0-rc.1`
        -    [] Review (ensure PR CI-checks are passing) and merge the PR (ensure merge CI-checks are passing)
        -    [] Build zip file ([workflow](https://github.com/woocommerce/woocommerce/actions/workflows/release-build-zip-file.yml))
        -    [] Validate version and stable tag in 'woocommerce.php' and `readme.txt` for the generated zip file

        #### Release to WordPress.org

        -    [] Skip notifying Atomic
        -    [] Using WooRelease, perform a release dry run with e.g., `php woorelease.php wporg:release --product_version=9.9.0-rc.1 --zip_file=ZIP_FILE_PATH --product_path=plugins/woocommerce https://github.com/woocommerce/woocommerce/tree/release/9.9`
        -    [] Using WooRelease, perform release with e.g., `php woorelease.php wporg:release --product_version=9.9.0-rc.1 --zip_file=ZIP_FILE_PATH --product_path=plugins/woocommerce https://github.com/woocommerce/woocommerce/tree/release/9.9 --release`
        -    [] If the release command reports SVN-related timeouts, validate versions on https://wordpress.org/plugins/woocommerce/advanced/ and https://plugins.svn.wordpress.org/woocommerce/tags/ pages and continue if those are correct
        -    [] Upon receiving email `[WordPress Plugin Directory] Pending release for WooCommerce`, confirm the release
        -    [] Verify the new version is listed and downloadable on https://wordpress.org/plugins/woocommerce/advanced/ page

        #### Stage and bump stable tag

        -    [] Manually create a release entry on https://github.com/woocommerce/woocommerce/releases (use version as tag, upload the generated zip, and pick the proper release branch)
        -    [] Verify new PRs created by `github-actions` and merge ones related to the release

        #### Send comms out

        -    [] Coordinate with the Developer Advocacy team updating the pre-release post on developer.woocommerce.com
        -    [] Notify #woo-core-releases and #woo-announcements Slack channels with a link to the release post
        -    [] Post an update in the internal release P2

        #### Post-release monitoring

        -    [] Follow post-release monitoring guidelines

  - type: markdown
    attributes:
      value: |
        ### Final release
        
        #### Get release artifact ready
        
        -    [] Validate stable tag in `readme.txt` for the release branch and update if necessary
        -    [] Validate stable tag in `readme.txt` for the SVN `trunk` ([here](https://plugins.svn.wordpress.org/woocommerce/trunk/readme.txt))
        -    [] Generate [changelog](https://github.com/woocommerce/woocommerce/blob/trunk/changelog.txt) ([workflow](https://github.com/woocommerce/woocommerce/actions/workflows/new-cfe-prr-pre-build-compile-changelog-file.yml))
        -    [] Create a PR to bump version in source code with `GITHUB_TOKEN=<your_PAT_token> pnpm utils code-freeze version-bump -b release/9.9 9.9.0`
        -    [] Review (ensure PR CI-checks are passing) and merge the PR (ensure merge CI-checks are passing)
        -    [] Build zip file ([workflow](https://github.com/woocommerce/woocommerce/actions/workflows/build-release-zip-file.yml))
        -    [] Validate version and stable tag in 'woocommerce.php' and `readme.txt` for the generated zip file

        #### Release to WordPress.org

        -    [] Notify Atomic (via P2 and Slack) before deploying release
        -    [] Using WooRelease, perform a release dry run with e.g., `php woorelease.php wporg:release --product_version=9.9.0 --zip_file=ZIP_FILE_PATH --product_path=plugins/woocommerce https://github.com/woocommerce/woocommerce/tree/release/9.9`
        -    [] Using WooRelease, perform release with e.g., `php woorelease.php wporg:release --product_version=9.9.0 --zip_file=ZIP_FILE_PATH --product_path=plugins/woocommerce https://github.com/woocommerce/woocommerce/tree/release/9.9 --release`
        -    [] If the release command reports SVN-related timeouts, validate versions on https://wordpress.org/plugins/woocommerce/advanced/ and https://plugins.svn.wordpress.org/woocommerce/tags/ pages and continue if those are correct
        -    [] Upon receiving email `[WordPress Plugin Directory] Pending release for WooCommerce`, confirm the release
        -    [] Verify the new version is listed and downloadable on https://wordpress.org/plugins/woocommerce/ page
        -    [] Update the Atomic comms threads about the release completion        

        #### Stage and bump stable tag

        -    [] For the next 4 hours, monitor the release staging: monitoring alerts (as per p1745322404770529/1745322371.115259-slack-C01DT6U03HC) and updates in the Atomic comms threads.
        -    [] Using WooRelease, perform the stable tag bump dry run with e.g., `php woorelease.php update-stable --product_path=plugins/woocommerce https://github.com/woocommerce/woocommerce/tree/trunk 9.9.0`
        -    [] Using WooRelease, perform the stable tag bump with e.g., `php woorelease.php update-stable --product_path=plugins/woocommerce https://github.com/woocommerce/woocommerce/tree/trunk 9.9.0 --update`
        -    [] Review (ensure PR CI-checks are passing) and merge additional PR (ensure merge CI-checks are passing) created on the previous step to sync stable tag with the source code
        -    [] Manually create a release entry on https://github.com/woocommerce/woocommerce/releases (use version as tag, upload the generated zip, and pick the proper release branch)
        -    [] Verify new PRs created by `github-actions` and merge ones related to the release

        #### Send comms out

        -    [] Coordinate with the Developer Advocacy team posting the release announcement on developer.woocommerce.com (post guidelines outlined here: Pf59Ax-7F-p2)
        -    [] Notify #woo-core-releases and #woo-announcements Slack channels of the release with a link to the internal release post
        -    [] Post an update in the internal release post

        #### Post-release monitoring

        -    [] Follow post-release monitoring guidelines

  - type: markdown
    attributes:
      value: |
        ### Dot-releases
        
        -    [] Ensure all [PRRs](https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22point%20release%20request%22) for the target release version are merged
        -    [] Follow `Final release` checklist
