<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api\Autogenerated;

/**
 * Tests for capability/access-attribute inheritance.
 *
 * The builder treats #[RequiredCapability] / #[PublicAccess] as inheritable
 * from three sources: parent classes, traits, and PHP interfaces. A direct
 * attribute on the class itself takes precedence; otherwise caps from every
 * source are merged. These tests verify both the generated check list and
 * the runtime behaviour.
 */
class AttributeInheritanceTest extends AutogeneratedTestCase {
	/**
	 * Read the autogenerated resolver source for a given query class.
	 *
	 * @param string $class_name The short PHP class name (e.g. `InheritedCapQuery`).
	 */
	private function read_generated_resolver( string $class_name ): string {
		$path = __DIR__ . '/../Fixtures/DummyApiAutogenerated/GraphQLQueries/' . $class_name . '.php';
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		return (string) file_get_contents( $path );
	}

	/**
	 * Assert that the generated resolver source contains an instantiation of
	 * RequiredCapability with the given capability slug.
	 *
	 * Generated form: `( new \...\RequiredCapability( 'cap' ) )->authorize( ... )`.
	 * Phrased loosely so it still matches if the linter shifts whitespace.
	 *
	 * @param string $capability The capability slug.
	 * @param string $source     The generated resolver source code.
	 */
	private function assertGeneratesRequiredCapability( string $capability, string $source ): void {
		$this->assertMatchesRegularExpression(
			'/new \\\\Automattic\\\\WooCommerce\\\\Api\\\\Attributes\\\\RequiredCapability\\(\s*\'' . preg_quote( $capability, '/' ) . '\'\s*\\)/',
			$source
		);
	}

	/**
	 * Assert that the generated resolver source does NOT contain an instantiation
	 * of RequiredCapability with the given capability slug.
	 *
	 * @param string $capability The capability slug.
	 * @param string $source     The generated resolver source code.
	 */
	private function assertDoesNotGenerateRequiredCapability( string $capability, string $source ): void {
		$this->assertDoesNotMatchRegularExpression(
			'/new \\\\Automattic\\\\WooCommerce\\\\Api\\\\Attributes\\\\RequiredCapability\\(\s*\'' . preg_quote( $capability, '/' ) . '\'\s*\\)/',
			$source
		);
	}

	/**
	 * @testdox a query class inherits #[RequiredCapability] from its abstract parent.
	 */
	public function test_required_capability_inherited_from_parent(): void {
		$source = $this->read_generated_resolver( 'InheritedCapQuery' );
		$this->assertGeneratesRequiredCapability( 'manage_options', $source );

		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );
		$ok = $this->execute_query( '{ inheritedCap { result } }' );
		$this->assertSame( 'inherited cap', $ok['data']['inheritedCap']['result'] ?? null );

		wp_set_current_user( 0 );
		$rejected = $this->execute_query( '{ inheritedCap { result } }' );
		// Anonymous -> UNAUTHORIZED (the caller could authenticate to gain access).
		$this->assertSame( 'UNAUTHORIZED', $rejected['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox a query class inherits #[PublicAccess] from a trait.
	 */
	public function test_public_access_inherited_from_trait(): void {
		$source = $this->read_generated_resolver( 'InheritedPublicQuery' );
		// PublicAccess inheritance short-circuits the attribute expression to
		// `true`, so the generated resolver carries no RequiredCapability
		// instantiation.
		$this->assertStringNotContainsString( 'RequiredCapability(', $source );

		wp_set_current_user( 0 );
		$result = $this->execute_query( '{ inheritedPublic { result } }' );

		$this->assertArrayNotHasKey( 'errors', $result );
		$this->assertSame( 'inherited public', $result['data']['inheritedPublic']['result'] ?? null );
	}

	/**
	 * @testdox a query class inherits #[RequiredCapability] from a PHP interface.
	 */
	public function test_required_capability_inherited_from_interface(): void {
		$source = $this->read_generated_resolver( 'InheritedFromInterfaceQuery' );
		$this->assertGeneratesRequiredCapability( 'manage_options', $source );

		wp_set_current_user( 0 );
		$result = $this->execute_query( '{ inheritedFromInterface { result } }' );
		// Anonymous -> UNAUTHORIZED.
		$this->assertSame( 'UNAUTHORIZED', $result['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox a direct attribute overrides any inherited capability.
	 */
	public function test_direct_attribute_overrides_inherited_capability(): void {
		$source = $this->read_generated_resolver( 'OverriddenCapQuery' );
		$this->assertGeneratesRequiredCapability( 'manage_categories', $source );
		$this->assertDoesNotGenerateRequiredCapability( 'manage_options', $source );

		// `editor` has manage_categories but NOT manage_options. If the
		// inherited cap were used, this would fail.
		$editor = self::factory()->user->create( array( 'role' => 'editor' ) );
		wp_set_current_user( $editor );
		$result = $this->execute_query( '{ overriddenCap { result } }' );
		$this->assertSame( 'overridden cap', $result['data']['overriddenCap']['result'] ?? null );

		// And the same editor still fails the inherited-cap variant — proving
		// the difference is real, not a permissive role.
		$inherited = $this->execute_query( '{ inheritedCap { result } }' );
		$this->assertSame( 'FORBIDDEN', $inherited['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox capabilities inherited from multiple sources are all enforced.
	 */
	public function test_capabilities_from_multiple_sources_are_merged(): void {
		$source = $this->read_generated_resolver( 'MergedCapsQuery' );
		// Both the parent's manage_options and the trait's edit_posts must
		// be present in the generated checks.
		$this->assertGeneratesRequiredCapability( 'manage_options', $source );
		$this->assertGeneratesRequiredCapability( 'edit_posts', $source );

		// `editor` has edit_posts but NOT manage_options -> must fail.
		$editor = self::factory()->user->create( array( 'role' => 'editor' ) );
		wp_set_current_user( $editor );
		$rejected = $this->execute_query( '{ mergedCaps { result } }' );
		$this->assertSame( 'FORBIDDEN', $rejected['errors'][0]['extensions']['code'] ?? null );

		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );
		$ok = $this->execute_query( '{ mergedCaps { result } }' );
		$this->assertSame( 'merged caps', $ok['data']['mergedCaps']['result'] ?? null );
	}
}
