<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api\Autogenerated;

/**
 * Tests for the authorize() method support: standalone, with #[Ignore],
 * combined with an inherited cap (override mode), and composed with a
 * direct cap via the $_preauthorized infrastructure parameter.
 */
class AuthorizeTest extends AutogeneratedTestCase {
	/**
	 * Read the autogenerated resolver source for a given query class.
	 *
	 * @param string $class_name The short PHP class name.
	 */
	private function read_generated_resolver( string $class_name ): string {
		$path = __DIR__ . '/../Fixtures/DummyApiAutogenerated/GraphQLQueries/' . $class_name . '.php';
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		return (string) file_get_contents( $path );
	}

	/**
	 * @testdox authorize() is the sole guard when no auth attribute is declared.
	 */
	public function test_authorize_only_query_uses_authorize_method(): void {
		$source = $this->read_generated_resolver( 'AuthorizeOnlyQuery' );
		$this->assertStringNotContainsString( 'check_current_user_can', $source );
		$this->assertStringContainsString( 'ResolverHelpers::authorize_command', $source );

		wp_set_current_user( 0 );

		$allowed = $this->execute_query( '{ authorizeOnly(allow: true) { result } }' );
		$this->assertSame( 'allowed', $allowed['data']['authorizeOnly']['result'] ?? null );

		$denied = $this->execute_query( '{ authorizeOnly(allow: false) { result } }' );
		// Anonymous principal + denied → UNAUTHORIZED (re-authenticating could change the outcome).
		$this->assertSame( 'UNAUTHORIZED', $denied['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox #[Ignore] on authorize() suppresses it; the cap check applies instead.
	 */
	public function test_ignored_authorize_method_is_skipped(): void {
		$source = $this->read_generated_resolver( 'IgnoredAuthorizeQuery' );
		// The autodiscovered RequiredCapability attribute is wired in; authorize_command is not.
		$this->assertMatchesRegularExpression(
			'/new \\\\Automattic\\\\WooCommerce\\\\Api\\\\Attributes\\\\RequiredCapability\\(\s*\'manage_options\'\s*\\)/',
			$source
		);
		$this->assertStringNotContainsString( 'authorize_command', $source );

		// Even though the fixture's authorize() returns false, an admin must
		// succeed — confirming the method is skipped at generation time.
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );
		$ok = $this->execute_query( '{ ignoredAuthorize { result } }' );
		$this->assertSame( 'cap enforced', $ok['data']['ignoredAuthorize']['result'] ?? null );

		wp_set_current_user( 0 );
		$rejected = $this->execute_query( '{ ignoredAuthorize { result } }' );
		// Anonymous → UNAUTHORIZED.
		$this->assertSame( 'UNAUTHORIZED', $rejected['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox a direct authorize() supersedes a cap inherited from a parent class.
	 */
	public function test_direct_authorize_overrides_inherited_capability(): void {
		$source = $this->read_generated_resolver( 'OverriddenAuthorizeQuery' );
		// The inherited manage_options cap MUST NOT be turned into a check —
		// authorize() takes over as the sole guard.
		$this->assertStringNotContainsString( 'check_current_user_can', $source );
		$this->assertStringContainsString( 'ResolverHelpers::authorize_command', $source );

		// `editor` has edit_posts but not manage_options. authorize() returns
		// true → succeeds despite the inherited cap pointing to manage_options.
		$editor = self::factory()->user->create( array( 'role' => 'editor' ) );
		wp_set_current_user( $editor );
		$ok = $this->execute_query( '{ overriddenAuthorize { result } }' );
		$this->assertSame( 'authorize wins', $ok['data']['overriddenAuthorize']['result'] ?? null );

		// `subscriber` has neither cap → authorize() returns false → rejected.
		$subscriber = self::factory()->user->create( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $subscriber );
		$rejected = $this->execute_query( '{ overriddenAuthorize { result } }' );
		$this->assertSame( 'FORBIDDEN', $rejected['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox $_preauthorized carries the result of the attribute-driven cap check into authorize().
	 */
	public function test_composed_authorize_receives_preauthorized_flag(): void {
		$source = $this->read_generated_resolver( 'ComposedAuthorizeQuery' );
		// The cap is NOT enforced as a standalone gate; instead its result is
		// passed to authorize() as `_preauthorized` via the generated
		// `compute_preauthorized()` helper that wraps the attribute call.
		$this->assertMatchesRegularExpression(
			'/\'_preauthorized\'\s*=>\s*self::compute_preauthorized\\(\s*\\$context\\[\'principal\'\\]\s*\\)/',
			$source
		);
		// And no standalone authorization gate — authorize() stays the sole
		// guard, with the attribute outcome flowing in via _preauthorized.
		$this->assertStringNotContainsString( 'Standalone authorization gate', $source );
		// The attribute call lives inside the compute_preauthorized() helper.
		$this->assertMatchesRegularExpression(
			'/public static function compute_preauthorized\\([^)]*\\): bool\\s*\\{\\s*return \\(\\s*new \\\\Automattic\\\\WooCommerce\\\\Api\\\\Attributes\\\\RequiredCapability\\(\s*\'manage_options\'\s*\\)\s*\\)->authorize\\(\s*\\$principal\s*\\);/',
			$source
		);

		// admin: has manage_options → _preauthorized=true → authorize returns true.
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );
		$admin_ok = $this->execute_query( '{ composedAuthorize { result } }' );
		$this->assertSame( 'composed', $admin_ok['data']['composedAuthorize']['result'] ?? null );

		// editor: lacks manage_options → _preauthorized=false, BUT has edit_posts
		// → authorize falls back to the secondary cap and still allows the call.
		$editor = self::factory()->user->create( array( 'role' => 'editor' ) );
		wp_set_current_user( $editor );
		$editor_ok = $this->execute_query( '{ composedAuthorize { result } }' );
		$this->assertSame( 'composed', $editor_ok['data']['composedAuthorize']['result'] ?? null );

		// anonymous: neither cap → authorize returns false → UNAUTHORIZED.
		wp_set_current_user( 0 );
		$rejected = $this->execute_query( '{ composedAuthorize { result } }' );
		$this->assertSame( 'UNAUTHORIZED', $rejected['errors'][0]['extensions']['code'] ?? null );
	}
}
