<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api\Autogenerated;

/**
 * End-to-end coverage for per-field authorization gates emitted into the
 * generated ObjectType resolvers.
 *
 * Fixture surface:
 *
 *  - `Widget::$caption` carries `#[RequiredCapability('manage_woocommerce')]`,
 *    so reading this field is gated by the WP `manage_woocommerce` capability.
 *  - `Widget::$tag_ids` carries `#[PublicAccess]`, which at field level emits
 *    a build warning and is treated as a no-op (allow-by-default). The
 *    generated resolver therefore has no gate on `tag_ids`.
 *
 * Field-level denies surface as a per-field error in the GraphQL response;
 * the field value becomes `null` and the rest of the type resolves normally.
 */
class FieldAuthorizeTest extends AutogeneratedTestCase {
	/**
	 * @testdox An admin can read a gated field — the gate grants and the value is returned.
	 */
	public function test_admin_can_read_gated_field(): void {
		$admin = self::factory()->user->create_and_get( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin->ID );

		$result = $this->execute_query( '{ publicWidget { caption } }' );

		$this->assertArrayNotHasKey( 'errors', $result, 'Admin should not see any errors when reading a gated field.' );
		$this->assertArrayHasKey( 'data', $result );
		$this->assertArrayHasKey( 'publicWidget', $result['data'] );
		// Caption is nullable in the fixture; admin still gets through the gate.
		$this->assertArrayHasKey( 'caption', $result['data']['publicWidget'] );
	}

	/**
	 * @testdox An anonymous principal hits a field-level deny when reading a gated field.
	 */
	public function test_anonymous_is_denied_on_gated_field(): void {
		wp_set_current_user( 0 );

		$result = $this->execute_query( '{ publicWidget { caption } }' );

		$this->assertArrayHasKey( 'errors', $result, 'Anonymous reader should hit the field-level gate.' );
		$this->assertNotEmpty( $result['errors'] );
		$this->assertArrayHasKey( 'extensions', $result['errors'][0] );
		$this->assertSame( 'UNAUTHORIZED', $result['errors'][0]['extensions']['code'] );

		// The field value is null but other fields on the same type resolve normally.
		$this->assertArrayHasKey( 'data', $result );
		$this->assertNull( $result['data']['publicWidget']['caption'] );
	}

	/**
	 * @testdox An authenticated principal without the required capability hits a FORBIDDEN deny.
	 */
	public function test_subscriber_is_forbidden_on_gated_field(): void {
		$subscriber = self::factory()->user->create_and_get( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $subscriber->ID );

		$result = $this->execute_query( '{ publicWidget { caption } }' );

		$this->assertArrayHasKey( 'errors', $result );
		$this->assertSame( 'FORBIDDEN', $result['errors'][0]['extensions']['code'] );
		$this->assertNull( $result['data']['publicWidget']['caption'] );
	}

	/**
	 * @testdox A field-level deny carries a structured subject payload identifying type, field, and attribute.
	 */
	public function test_field_deny_carries_subject_payload(): void {
		wp_set_current_user( 0 );

		$result = $this->execute_query( '{ publicWidget { caption } }' );

		$this->assertArrayHasKey( 'errors', $result );
		$this->assertArrayHasKey( 'extensions', $result['errors'][0] );
		$this->assertArrayHasKey( 'subject', $result['errors'][0]['extensions'] );

		$subject = $result['errors'][0]['extensions']['subject'];
		$this->assertSame( 'Widget', $subject['type'] );
		$this->assertSame( 'caption', $subject['field'] );
		$this->assertSame( 'RequiredCapability', $subject['attribute'] );
	}

	/**
	 * @testdox A query that does not select the gated field is unaffected by its gate.
	 */
	public function test_unselected_gated_field_does_not_fire_gate(): void {
		wp_set_current_user( 0 );

		$result = $this->execute_query( '{ publicWidget { id slug } }' );

		$this->assertArrayNotHasKey( 'errors', $result );
		$this->assertSame( 'alpha', $result['data']['publicWidget']['slug'] );
	}

	/**
	 * @testdox A field decorated with #[PublicAccess] alone has no gate (warned and ignored at build).
	 */
	public function test_public_access_property_has_no_gate(): void {
		wp_set_current_user( 0 );

		$result = $this->execute_query( '{ publicWidget { tag_ids } }' );

		$this->assertArrayNotHasKey( 'errors', $result, 'PublicAccess at field level is a build-only marker; no runtime gate should fire.' );
		$this->assertSame( array( 1, 2, 3 ), $result['data']['publicWidget']['tag_ids'] );
	}
}
