<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api\Autogenerated;

/**
 * Tests for the `_principal` infrastructure parameter on authorize() and execute().
 *
 * The principal flows in through the resolver `$context` populated by the
 * controller (or, in these tests, by {@see AutogeneratedTestCase::execute_query()}
 * mirroring the controller). The principal channel is non-nullable end-to-end:
 * anonymous requests are represented by a sentinel principal (a Principal
 * wrapping a WP_User with ID === 0), not by null.
 */
class PrincipalParamTest extends AutogeneratedTestCase {
	/**
	 * @testdox $_principal on execute() receives the resolved Principal carrying the authenticated user.
	 */
	public function test_principal_aware_query_receives_authenticated_user(): void {
		$user_id = self::factory()->user->create(
			array(
				'user_login' => 'alice',
				'role'       => 'subscriber',
			)
		);
		wp_set_current_user( $user_id );

		$result = $this->execute_query( '{ principalAware { result } }' );

		$this->assertArrayNotHasKey( 'errors', $result );
		$this->assertSame( 'alice', $result['data']['principalAware']['result'] ?? null );
	}

	/**
	 * @testdox $_principal on execute() receives a sentinel anonymous principal for unauthenticated requests.
	 */
	public function test_principal_aware_query_receives_anonymous_principal(): void {
		wp_set_current_user( 0 );

		$result = $this->execute_query( '{ principalAware { result } }' );

		$this->assertArrayNotHasKey( 'errors', $result );
		$this->assertSame( 'anonymous', $result['data']['principalAware']['result'] ?? null );
	}

	/**
	 * @testdox the autogenerated resolver wires `_principal` into execute_args from $context.
	 */
	public function test_resolver_source_wires_principal_from_context(): void {
		$source = (string) file_get_contents( __DIR__ . '/../Fixtures/DummyApiAutogenerated/GraphQLQueries/PrincipalAwareQuery.php' );
		$this->assertStringContainsString(
			"\$execute_args['_principal'] = \$context['principal'];",
			$source
		);
	}
}
