export const SIMPLE_VIRTUAL_PRODUCT_NAME = 'Album';
export const SIMPLE_PHYSICAL_PRODUCT_NAME = 'Beanie';
export const FREE_SHIPPING_NAME = 'Free shipping';
export const FREE_SHIPPING_PRICE = 'Free';
export const FLAT_RATE_SHIPPING_NAME = 'Flat rate shipping';
export const FLAT_RATE_SHIPPING_PRICE = '$10.00';
export const DISCOUNTED_PRODUCT_NAME = 'Cap';
export const REGULAR_PRICED_PRODUCT_NAME = 'Polo';
export const INVALID_COUPON = 'invalidcoupon';
