export const TYPES = {
	RECEIVE_REGISTERED_CHANNELS_SUCCESS:
		'RECEIVE_REGISTERED_CHANNELS_SUCCESS' as const,
	RECEIVE_REGISTERED_CHANNELS_ERROR:
		'RECEIVE_REGISTERED_CHANNELS_ERROR' as const,
	RECEIVE_RECOMMENDED_CHANNELS_SUCCESS:
		'RECEIVE_RECOMMENDED_CHANNELS_SUCCESS' as const,
	RECEIVE_RECOMMENDED_CHANNELS_ERROR:
		'RECEIVE_RECOMMENDED_CHANNELS_ERROR' as const,
	RECEIVE_CAMPAIGNS_SUCCESS: 'RECEIVE_CAMPAIGNS_SUCCESS' as const,
	RECEIVE_CAMPAIGNS_ERROR: 'RECEIVE_CAMPAIGNS_ERROR' as const,
	RECEIVE_CAMPAIGN_TYPES_SUCCESS: 'RECEIVE_CAMPAIGN_TYPES_SUCCESS' as const,
	RECEIVE_CAMPAIGN_TYPES_ERROR: 'RECEIVE_CAMPAIGN_TYPES_ERROR' as const,
};
