export const TYPES = {
	RECEIVE_CHANNELS_SUCCESS: 'RECEIVE_CHANNELS_SUCCESS' as const,
	RECEIVE_CHANNELS_ERROR: 'RECEIVE_CHANNELS_ERROR' as const,
	RECEIVE_RECOMMENDED_CHANNELS_SUCCESS:
		'RECEIVE_RECOMMENDED_CHANNELS_SUCCESS' as const,
	RECEIVE_RECOMMENDED_CHANNELS_ERROR:
		'RECEIVE_RECOMMENDED_CHANNELS_ERROR' as const,
};
