<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

/**
 * GraphQL type for the OrdinalNumber enum type class.
 */
class OrdinalNumberType extends \GraphQL\Type\Definition\EnumType {
	public function __construct() {
		$config = array(
			'name'        => 'OrdinalNumber',
			'description' => __( 'Just some ordinal numbers.', 'woocommerce' ),
			'values'      => array(
				'FIRST'  => array(
					'value'       => 1,
					'description' => __( 'The first ordinal value.', 'woocommerce' ),
				),
				'SECOND' => array(
					'value'       => 2,
					'description' => __( 'The second ordinal value.', 'woocommerce' ),
				),
				'THIRD'  => array(
					'value' => 3,
				),
			),
		);

		parent::__construct( $config );
	}
}

// Autogenerated file, don't modify manually!
