<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQLController;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL type for the RecursiveType object type class.
 */
class RecursiveTypeType extends \GraphQL\Type\Definition\ObjectType {
	public function __construct() {
		$config = array(
			'name'        => 'RecursiveType',
			'description' => __( 'RecursiveType object type', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'interfaces'  => array(),
		);

		parent::__construct( $config );
	}

	public function get_fields() {
		$fields = array(
			'the_int'            => fn() => array(
				'type' => Type::nonNull( Type::int() ),
			),
			'the_recursive_type' => fn() => array(
				'type' => GraphQLController::resolve_type( 'RecursiveType' ),
			),
		);

		return $fields;
	}
}

// Autogenerated file, don't modify manually!
