<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQLController;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL type for the User object type class.
 */
class UserType extends \GraphQL\Type\Definition\ObjectType {
	public function __construct() {
		$config = array(
			'name'        => 'User',
			'description' => __( 'User object type', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'interfaces'  => array(),
		);

		parent::__construct( $config );
	}

	public function get_fields() {
		$fields = array(
			'id'    => fn() => array(
				'type' => Type::nonNull( Type::int() ),
			),
			'login' => fn() => array(
				'type' => Type::nonNull( Type::string() ),
			),
			'email' => fn() => array(
				'type' => Type::nonNull( Type::string() ),
			),
		);

		return $fields;
	}
}

// Autogenerated file, don't modify manually!
