<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQLController;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL type for the Webhook object type class.
 */
class WebhookType extends \GraphQL\Type\Definition\ObjectType {
	public function __construct() {
		$config = array(
			'name'        => 'Webhook',
			'description' => __( 'Represents a full webhook, including static definition and current status.', 'woocommerce' ),
			'fields'      => $this->get_fields(),
			'interfaces'  => array(
				GraphQLController::resolve_type( 'WebhookDefinition' ),
			),
		);

		parent::__construct( $config );
	}

	public function get_fields() {
		$fields = array(
			'id'               => fn() => array(
				'type' => Type::nonNull( Type::int() ),
			),
			'failure_count'    => fn() => array(
				'type' => Type::nonNull( Type::int() ),
			),
			'pending_delivery' => fn() => array(
				'type' => Type::nonNull( Type::boolean() ),
			),
			'date_created'     => fn() => array(
				'type' => Type::nonNull( Type::string() ),
			),
			'status'           => fn() => array(
				'type' => Type::nonNull( GraphQLController::resolve_type( 'WebhookStatus' ) ),
			),
			'user'             => fn() => array(
				'type' => GraphQLController::resolve_type( 'User' ),
			),
		);
		$fields = array_merge( $fields, GraphQLController::resolve_type( 'WebhookDefinition' )->get_fields() );
		return $fields;
	}
}

// Autogenerated file, don't modify manually!
