<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Input;

use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Enums\Color as ColorType;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Scalars\DummyDateTime as DummyDateTimeType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\InputObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class CreateWidget {
	private static ?InputObjectType $instance = null;

	public static function get(): InputObjectType {
		if ( null === self::$instance ) {
			self::$instance = new InputObjectType(
				array(
					'name'        => 'CreateWidgetInput',
					'description' => __( 'Data needed to create a new widget', 'woocommerce' ),
					'fields'      => fn() => array(
						'label'      => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The widget label', 'woocommerce' ),
						),
						'weight'     => array(
							'type'        => Type::int(),
							'description' => __( 'Optional weight in grams', 'woocommerce' ),
						),
						'color'      => array(
							'type'        => Type::nonNull( ColorType::get() ),
							'description' => __( 'The widget color', 'woocommerce' ),
						),
						'tag_ids'    => array(
							'type'        => Type::listOf( Type::nonNull( Type::int() ) ),
							'description' => __( 'Tag IDs to attach to the widget', 'woocommerce' ),
						),
						'expires_at' => array(
							'type'        => DummyDateTimeType::get(),
							'description' => __( 'When the widget should expire', 'woocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
