<?php

namespace Nette\Security\Diagnostics;

use Nette,
	Nette\Diagnostics\Helpers;

?>
<style>

	#nette-debug .nette-UserPanel pre {
		background: #FDF5CE;
		padding: .4em .7em;
		border: 1px dotted silver;
		overflow: auto;
	}

</style>

<div class="nette-UserPanel">
	<h1><?php if ($this->user->isLoggedIn()): ?>Logged in<?php else: ?>Unlogged<?php endif ?></h1>

	<?php if ($this->user->getIdentity()): echo Helpers::clickableDump($this->user->getIdentity()); else: ?><p>no identity</p><?php endif ?>
</div>
