<?php
declare( strict_types = 1 );

namespace Automattic\WooCommerce\Blocks\BlockTypes;

/**
 * Product Filter: Dropdown Block.
 */
final class ProductFilterDropdown extends AbstractBlock {

	use EnableBlockJsonAssetsTrait;

	/**
	 * Block name.
	 *
	 * @var string
	 */
	protected $block_name = 'product-filter-dropdown';

	/**
	 * Render the block.
	 *
	 * @param array    $attributes Block attributes.
	 * @param string   $content    Block content.
	 * @param WP_Block $block      Block instance.
	 * @return string Rendered block type output.
	 */
	protected function render( $attributes, $content, $block ): string {
		if (
			empty( $block->context['filterData'] )
		) {
			return '';
		}

		$items       = $block->context['filterData']['items'] ?? array();
		$show_counts = $block->context['filterData']['showCounts'] ?? false;
		$classes     = '';
		$style       = '';

		$tags = new \WP_HTML_Tag_Processor( $content );
		if ( $tags->next_tag( array( 'class_name' => 'wc-block-product-filter-dropdown' ) ) ) {
			$classes = $tags->get_attribute( 'class' );
			$style   = $tags->get_attribute( 'style' );
		}

		$selected_items = array_filter(
			$items,
			function ( $item ) {
				return $item['selected'];
			}
		);

		// Map selected items to only include label and value properties expected by frontend.
		$selected_items_for_context = array_values(
			array_map(
				function ( $item ) {
					return [
						'label' => $item['label'],
						'value' => $item['value'],
						'type'  => $item['type'],
					];
				},
				$selected_items
			)
		);

		/* translators: %s: filter group label. */
		$placeholder = sprintf( __( 'Select %s', 'woocommerce' ), $block->context['filterData']['groupLabel'] ?? '' );

		$wrapper_attributes = array(
			'data-wp-interactive' => 'woocommerce/product-filters',
			'data-wp-key'         => wp_unique_prefixed_id( $this->get_full_block_name() ),
			'data-wp-context'     => wp_json_encode(
				[
					'selectedItems'      => $selected_items_for_context,
					'isOpen'             => false,
					'defaultPlaceholder' => $placeholder,
				],
				JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP
			),
			'class'               => esc_attr( $classes ),
		);

		if ( ! empty( $style ) ) {
			// Styles generated by Supports API doesn't include semicolon at the end.
			$wrapper_attributes['style'] = esc_attr( $style ) . ';';
		}

		ob_start();
		?>
		<div <?php echo get_block_wrapper_attributes( $wrapper_attributes ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
			<div class="wc-block-product-filter-dropdown" data-wp-on--click="actions.toggleIsOpen" data-wp-on-document--click="actions.handleClickOutside">
				<div class="wc-block-product-filter-dropdown__dropdown" tabindex="-1" >
					<div
						class="wc-block-product-filter-dropdown__dropdown-selection"
						id="options-dropdown"
						tabindex="0"
						role="button"
						aria-haspopup="listbox"
						aria-expanded="false"
						data-wp-bind--aria-expanded="context.isOpen"
					>
						<span class="wc-block-product-filter-dropdown__placeholder" data-wp-text="state.placeholderText">
							<?php echo empty( $selected_items ) ? esc_html( $placeholder ) : ''; ?>
						</span>
						<div class="selected-options">
							<template
									data-wp-each="context.selectedItems"
									data-wp-each-key="context.item.value"
								>
									<div class="wc-block-product-filter-dropdown__selected-badge">
										<span class="wc-block-product-filter-dropdown__badge-text" data-wp-text="context.item.label"></span>
										<svg
											data-wp-on--click---unselect-item="actions.unselectDropdownItem"
											data-wp-on--click---parent-action="actions.toggleFilter"
											class="wc-block-product-filter-dropdown__badge-remove"
											width="24"
											height="24"
											xmlns="http://www.w3.org/2000/svg"
											viewBox="0 0 24 24"
											aria-hidden="true"
										>
											<path d="M12 13.06l3.712 3.713 1.061-1.06L13.061 12l3.712-3.712-1.06-1.06L12 10.938 8.288 7.227l-1.061 1.06L10.939 12l-3.712 3.712 1.06 1.061L12 13.061z"></path>
										</svg>
									</div>
							</template>

							<?php foreach ( $selected_items as $selected ) { ?>
								<div
									class="wc-block-product-filter-dropdown__selected-badge"
									data-wp-key="<?php echo esc_attr( $selected['value'] ); ?>"
									data-wp-each-child
								>
										<span class="wc-block-product-filter-dropdown__badge-text"><?php echo esc_html( $selected['label'] ); ?></span>
										<svg
											data-wp-on--click---unselect-item="actions.unselectDropdownItem"
											data-wp-on--click---parent-action="actions.toggleFilter"
											class="wc-block-product-filter-dropdown__badge-remove"
											width="24"
											height="24"
											xmlns="http://www.w3.org/2000/svg"
											viewBox="0 0 24 24"
											aria-hidden="true"
										>
											<path d="M12 13.06l3.712 3.713 1.061-1.06L13.061 12l3.712-3.712-1.06-1.06L12 10.938 8.288 7.227l-1.061 1.06L10.939 12l-3.712 3.712 1.06 1.061L12 13.061z"></path>
										</svg>
								</div>
							<?php } ?>
						</div>
						<span class="wc-block-product-filter-dropdown__svg-container">
							<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="30" height="30" >
								<path d="M17.5 11.6L12 16l-5.5-4.4.9-1.2L12 14l4.5-3.6 1 1.2z" ></path>
							</svg>
						</span>
					</div>
					<div
						class="wc-block-product-filter-dropdown__dropdown-list"
						aria-labelledby="options-dropdown"
						role="listbox"
						data-wp-bind--hidden="!context.isOpen"
						hidden
					>
						<?php foreach ( $items as $item ) { ?>
							<?php $item_id = $item['type'] . '-' . $item['value']; ?>
							<div
								class="wc-block-product-filter-dropdown__dropdown-option"
								role="option"
								tabindex="0"
								aria-label="<?php echo esc_attr( $this->get_aria_label( $item, $show_counts ) ); ?>"
								data-wp-on--click---select-item="actions.selectDropdownItem"
								data-wp-on--click---parent-action="actions.toggleFilter"
								data-wp-class--is-selected="state.isFilterSelected"
								data-wp-bind--aria-selected="state.isFilterSelected"
								data-wp-key="<?php echo esc_attr( $item_id ); ?>"
								<?php echo wp_interactivity_data_wp_context( array( 'item' => $item ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
							>
								<?php echo $item['label']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>

								<?php if ( $show_counts ) : ?>
									<span class="wc-block-product-filter-dropdown__count">
										(<?php echo esc_html( $item['count'] ); ?>)
									</span>
								<?php endif; ?>
							</div>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
		<?php
		return ob_get_clean();
	}

	/**
	 * Get aria label for filter item.
	 *
	 * @param array $item Filter item.
	 * @param bool  $show_counts Whether to show counts.
	 *
	 * @return string Aria label.
	 */
	private function get_aria_label( array $item, bool $show_counts ): string {
		if ( $show_counts ) {
			return sprintf(
				/* translators: %1$s: Product filter name, %2$d: Number of products */
				_n(
					'%1$s (%2$d product)',
					'%1$s (%2$d products)',
					$item['count'],
					'woocommerce'
				),
				$item['ariaLabel'] ?? $item['label'],
				$item['count']
			);
		}

		return $item['ariaLabel'] ?? $item['label'];
	}
}
