<?php
declare( strict_types = 1 );

namespace Automattic\WooCommerce\Blocks\BlockTypes;

/**
 * Product Filter: Checkbox List Block.
 */
final class ProductFilterCheckboxList extends AbstractBlock {

	use EnableBlockJsonAssetsTrait;

	/**
	 * Block name.
	 *
	 * @var string
	 */
	protected $block_name = 'product-filter-checkbox-list';

	/**
	 * Default number of items to show before "Show more" button.
	 *
	 * @var int
	 */
	const DISPLAY_LIMIT = 15;

	/**
	 * Render the block.
	 *
	 * @param array    $attributes Block attributes.
	 * @param string   $content    Block content.
	 * @param WP_Block $block      Block instance.
	 * @return string Rendered block type output.
	 */
	protected function render( $attributes, $content, $block ) {
		if ( empty( $block->context['woocommerce/selectableItems'] ) ) {
			return '';
		}

		$block_context   = $block->context['woocommerce/selectableItems'];
		$items           = $block_context['items'] ?? array();
		$store_namespace = $block_context['storeNamespace'] ?? 'woocommerce/product-filters';
		$display_limit   = self::DISPLAY_LIMIT;
		$classes         = '';
		$style           = '';

		$tags = new \WP_HTML_Tag_Processor( $content );
		if ( $tags->next_tag( array( 'class_name' => 'wc-block-product-filter-checkbox-list' ) ) ) {
			$classes = $tags->get_attribute( 'class' );
			$style   = $tags->get_attribute( 'style' );
		}

		$wrapper_attributes = array(
			'data-wp-interactive' => 'woocommerce/product-filter-checkbox-list',
			'data-wp-key'         => wp_unique_prefixed_id( $this->get_full_block_name() ),
			'class'               => esc_attr( $classes ),
		);

		if ( ! empty( $style ) ) {
			// Styles generated by Supports API doesn't include semicolon at the end.
			$wrapper_attributes['style'] = esc_attr( $style ) . ';';
		}

		$checkbox_svg   = '<svg class="wc-block-product-filter-checkbox-list__mark" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">'
			. '<path d="M9.25 1.19922L3.75 6.69922L1 3.94922" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>'
			. '</svg>';
		$has_more_items = count( $items ) > $display_limit;
		$hidden_count   = max( 0, count( $items ) - $display_limit );

		ob_start();
		?>
		<div <?php echo get_block_wrapper_attributes( $wrapper_attributes ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
			<fieldset>
				<?php if ( ! empty( $block_context['groupLabel'] ) ) : ?>
					<legend class="screen-reader-text"><?php echo esc_html( $block_context['groupLabel'] ); ?></legend>
				<?php endif; ?>
				<div
					class="wc-block-product-filter-checkbox-list__items"
					data-wp-interactive="<?php echo esc_attr( $store_namespace ); ?>"
				>
					<?php
					$index = 0;
					foreach ( $items as $item ) :
						$is_hidden = $index >= $display_limit;
						++$index;
						?>
						<div
							class="wc-block-product-filter-checkbox-list__item"
							<?php echo wp_interactivity_data_wp_context( array( 'item' => $item ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
							<?php if ( $is_hidden ) : ?>
								hidden
								data-wp-bind--hidden="!state.isExpanded"
							<?php endif; ?>
						>
							<label
								class="wc-block-product-filter-checkbox-list__label"
								for="<?php echo esc_attr( $item['id'] ); ?>"
							>
								<span class="wc-block-product-filter-checkbox-list__input-wrapper">
									<input
										id="<?php echo esc_attr( $item['id'] ); ?>"
										class="wc-block-product-filter-checkbox-list__input"
										type="checkbox"
										<?php if ( ! empty( $item['ariaLabel'] ) ) : ?>
											aria-label="<?php echo esc_attr( $item['ariaLabel'] ); ?>"
										<?php endif; ?>
										data-wp-on--change="actions.toggle"
										value="<?php echo esc_attr( $item['value'] ); ?>"
										<?php checked( ! empty( $item['selected'] ) ); ?>
										data-wp-bind--checked="state.isSelected"
									>
									<?php echo $checkbox_svg; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
								</span>
								<span class="wc-block-product-filter-checkbox-list__text-wrapper">
									<span class="wc-block-product-filter-checkbox-list__text">
										<?php echo wp_kses( $item['label'], $this->get_allowed_label_html() ); ?>
									</span>
									<?php if ( isset( $item['count'] ) ) : ?>
										<span class="wc-block-product-filter-checkbox-list__count">
											(<?php echo esc_html( $item['count'] ); ?>)
										</span>
									<?php endif; ?>
								</span>
							</label>
						</div>
					<?php endforeach; ?>
				</div>
				<?php if ( $has_more_items ) : ?>
					<div class="wc-block-product-filter-checkbox-list__show-more">
						<button
							type="button"
							class="wc-block-product-filter-checkbox-list__show-more-button"
							data-wp-on--click="actions.toggleShowMore"
							data-wp-text="state.showMoreLabel"
							data-wp-bind--hidden="state.isExpanded"
						>
							<?php
							/* translators: %d: number of hidden items */
							echo esc_html( sprintf( __( 'Show %d more', 'woocommerce' ), $hidden_count ) );
							?>
						</button>
					</div>
				<?php endif; ?>
			</fieldset>
		</div>
		<?php
		return ob_get_clean();
	}

	/**
	 * Disable the style handle for this block type. We use block.json to load the style.
	 *
	 * @return null
	 */
	protected function get_block_type_style() {
		return null;
	}

	/**
	 * Get allowed HTML for item labels, including SVG for rating stars.
	 *
	 * @return array Allowed HTML elements and attributes.
	 */
	private function get_allowed_label_html() {
		return array_merge(
			wp_kses_allowed_html( 'post' ),
			array(
				'svg'  => array(
					'class'      => true,
					'xmlns'      => true,
					'width'      => true,
					'height'     => true,
					'viewbox'    => true,
					'fill'       => true,
					'aria-label' => true,
				),
				'path' => array(
					'd'            => true,
					'fill'         => true,
					'stroke'       => true,
					'stroke-width' => true,
					'transform'    => true,
				),
			)
		);
	}
}
