<?php
declare( strict_types = 1 );

namespace Automattic\WooCommerce\Blocks\BlockTypes;

/**
 * Product Filter: Checkbox List Block.
 */
final class ProductFilterCheckboxList extends AbstractBlock {

	use EnableBlockJsonAssetsTrait;

	/**
	 * Block name.
	 *
	 * @var string
	 */
	protected $block_name = 'product-filter-checkbox-list';

	/**
	 * Render the block.
	 *
	 * @param array    $attributes Block attributes.
	 * @param string   $content    Block content.
	 * @param WP_Block $block      Block instance.
	 * @return string Rendered block type output.
	 */
	protected function render( $attributes, $content, $block ) {
		if ( empty( $block->context['woocommerce/selectableItems'] ) ) {
			return '';
		}

		$block_context   = $block->context['woocommerce/selectableItems'];
		$items           = $block_context['items'] ?? array();
		$store_namespace = $block_context['storeNamespace'] ?? 'woocommerce/product-filters';
		$select_action   = $block_context['selectAction'] ?? 'toggleFilter';
		$dynamic_items   = $block_context['dynamicItems'] ?? true;
		$classes         = '';
		$style           = '';

		$tags = new \WP_HTML_Tag_Processor( $content );
		if ( $tags->next_tag( array( 'class_name' => 'wc-block-product-filter-checkbox-list' ) ) ) {
			$classes = $tags->get_attribute( 'class' );
			$style   = $tags->get_attribute( 'style' );
		}

		$visible_items = array_values(
			array_filter(
				$items,
				function ( $item ) {
					return empty( $item['hidden'] );
				}
			)
		);

		$wrapper_attributes = array(
			'data-wp-interactive' => $store_namespace,
			'data-wp-key'         => wp_unique_prefixed_id( $this->get_full_block_name() ),
			'class'               => esc_attr( $classes ),
		);

		if ( ! empty( $style ) ) {
			// Styles generated by Supports API doesn't include semicolon at the end.
			$wrapper_attributes['style'] = esc_attr( $style ) . ';';
		}

		$checkbox_svg = '<svg class="wc-block-product-filter-checkbox-list__mark" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">'
			. '<path d="M9.25 1.19922L3.75 6.69922L1 3.94922" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>'
			. '</svg>';

		ob_start();
		?>
		<div <?php echo get_block_wrapper_attributes( $wrapper_attributes ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
			<fieldset>
				<?php if ( ! empty( $block_context['groupLabel'] ) ) : ?>
					<legend class="screen-reader-text"><?php echo esc_html( $block_context['groupLabel'] ); ?></legend>
				<?php endif; ?>
				<div class="wc-block-product-filter-checkbox-list__items">
					<?php if ( $dynamic_items ) : ?>
						<template
							data-wp-each--item="context.items"
							data-wp-each-key="context.item.id"
						>
							<div
								class="wc-block-product-filter-checkbox-list__item"
								data-wp-bind--hidden="context.item.hidden"
							>
								<label
									class="wc-block-product-filter-checkbox-list__label"
									data-wp-bind--for="context.item.id"
								>
									<span class="wc-block-product-filter-checkbox-list__input-wrapper">
										<input
											class="wc-block-product-filter-checkbox-list__input"
											type="checkbox"
											data-wp-bind--id="context.item.id"
											data-wp-bind--aria-label="context.item.ariaLabel"
											data-wp-on--change="actions.<?php echo esc_attr( $select_action ); ?>"
											data-wp-bind--value="context.item.value"
											data-wp-bind--checked="context.item.selected"
										>
										<?php echo $checkbox_svg; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
									</span>
									<span class="wc-block-product-filter-checkbox-list__text-wrapper">
										<span class="wc-block-product-filter-checkbox-list__text" data-wp-text="context.item.label"></span>
										<span
											class="wc-block-product-filter-checkbox-list__count"
											data-wp-bind--hidden="!context.item.count"
										> (<span data-wp-text="context.item.count"></span>)</span>
									</span>
								</label>
							</div>
						</template>
					<?php endif; ?>
					<?php foreach ( $visible_items as $item ) { ?>
						<div
							class="wc-block-product-filter-checkbox-list__item"
							<?php if ( $dynamic_items ) : ?>
								data-wp-each-child
								<?php echo wp_interactivity_data_wp_context( array( 'item' => $item ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
							<?php endif; ?>
						>
							<label
								class="wc-block-product-filter-checkbox-list__label"
								for="<?php echo esc_attr( $item['id'] ); ?>"
							>
								<span class="wc-block-product-filter-checkbox-list__input-wrapper">
									<input
										id="<?php echo esc_attr( $item['id'] ); ?>"
										class="wc-block-product-filter-checkbox-list__input"
										type="checkbox"
										<?php if ( ! empty( $item['ariaLabel'] ) ) : ?>
											aria-label="<?php echo esc_attr( $item['ariaLabel'] ); ?>"
										<?php endif; ?>
										data-wp-on--change="actions.<?php echo esc_attr( $select_action ); ?>"
										value="<?php echo esc_attr( $item['value'] ); ?>"
										data-wp-bind--checked="context.item.selected"
									>
									<?php echo $checkbox_svg; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
								</span>
								<span class="wc-block-product-filter-checkbox-list__text-wrapper">
									<span class="wc-block-product-filter-checkbox-list__text">
										<?php echo $item['label']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
									</span>
									<?php if ( isset( $item['count'] ) ) : ?>
										<span class="wc-block-product-filter-checkbox-list__count">
											 (<?php echo esc_html( $item['count'] ); ?>)
										</span>
									<?php endif; ?>
								</span>
							</label>
						</div>
					<?php } ?>
				</div>
			</fieldset>
		</div>
		<?php
		return ob_get_clean();
	}

	/**
	 * Disable the style handle for this block type. We use block.json to load the style.
	 *
	 * @return null
	 */
	protected function get_block_type_style() {
		return null;
	}
}
