<?php
declare( strict_types = 1 );

namespace Automattic\WooCommerce\Blocks\BlockTypes;

/**
 * Product Filter: Chips Block.
 */
final class ProductFilterChips extends AbstractBlock {

	use EnableBlockJsonAssetsTrait;

	/**
	 * Block name.
	 *
	 * @var string
	 */
	protected $block_name = 'product-filter-chips';

	/**
	 * Default number of items to show before "Show more" button.
	 *
	 * @var int
	 */
	const DISPLAY_LIMIT = 15;

	/**
	 * Render the block.
	 *
	 * @param array    $attributes Block attributes.
	 * @param string   $content    Block content.
	 * @param WP_Block $block      Block instance.
	 * @return string Rendered block type output.
	 */
	protected function render( $attributes, $content, $block ) {
		if ( empty( $block->context['woocommerce/selectableItems'] ) ) {
			return '';
		}

		$block_context   = $block->context['woocommerce/selectableItems'];
		$items           = $block_context['items'] ?? array();
		$store_namespace = $block_context['storeNamespace'] ?? 'woocommerce/product-filters';
		$display_limit   = self::DISPLAY_LIMIT;
		$classes         = '';
		$style           = '';

		$tags = new \WP_HTML_Tag_Processor( $content );
		if ( $tags->next_tag( array( 'class_name' => 'wc-block-product-filter-chips' ) ) ) {
			$classes = $tags->get_attribute( 'class' );
			$style   = $tags->get_attribute( 'style' );
		}

		$wrapper_attributes = array(
			'data-wp-interactive' => 'woocommerce/product-filter-chips',
			'data-wp-key'         => wp_unique_prefixed_id( $this->get_full_block_name() ),
			'class'               => esc_attr( $classes ),
		);

		if ( ! empty( $style ) ) {
			// Styles generated by Supports API doesn't include semicolon at the end.
			$wrapper_attributes['style'] = esc_attr( $style ) . ';';
		}

		$has_more_items = count( $items ) > $display_limit;
		$hidden_count   = max( 0, count( $items ) - $display_limit );

		ob_start();
		?>
		<div <?php echo get_block_wrapper_attributes( $wrapper_attributes ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
			<fieldset>
				<?php if ( ! empty( $block_context['groupLabel'] ) ) : ?>
					<legend class="screen-reader-text"><?php echo esc_html( $block_context['groupLabel'] ); ?></legend>
				<?php endif; ?>
				<div
					class="wc-block-product-filter-chips__items"
					data-wp-interactive="<?php echo esc_attr( $store_namespace ); ?>"
				>
					<?php
					$index = 0;
					foreach ( $items as $item ) :
						$is_hidden = $index >= $display_limit;
						++$index;
						?>
						<button
							class="wc-block-product-filter-chips__item"
							type="button"
							role="checkbox"
							id="<?php echo esc_attr( $item['id'] ); ?>"
							<?php if ( ! empty( $item['ariaLabel'] ) ) : ?>
								aria-label="<?php echo esc_attr( $item['ariaLabel'] ); ?>"
							<?php endif; ?>
							data-wp-on--click="actions.toggle"
							value="<?php echo esc_attr( $item['value'] ); ?>"
							aria-checked="<?php echo ! empty( $item['selected'] ) ? 'true' : 'false'; ?>"
							data-wp-bind--aria-checked="state.isSelected"
							<?php echo wp_interactivity_data_wp_context( array( 'item' => $item ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
							<?php if ( $is_hidden ) : ?>
								hidden
								data-wp-bind--hidden="!state.isExpanded"
							<?php endif; ?>
						>
							<span class="wc-block-product-filter-chips__label">
								<span class="wc-block-product-filter-chips__text">
									<?php echo wp_kses( $item['label'], $this->get_allowed_label_html() ); ?>
								</span>
								<?php if ( isset( $item['count'] ) ) : ?>
									<span class="wc-block-product-filter-chips__count">
										(<?php echo esc_html( $item['count'] ); ?>)
									</span>
								<?php endif; ?>
							</span>
						</button>
					<?php endforeach; ?>
					<?php if ( $has_more_items ) : ?>
						<button
							type="button"
							class="wc-block-product-filter-chips__show-more"
							data-wp-on--click="woocommerce/product-filter-chips::actions.toggleShowMore"
							data-wp-text="woocommerce/product-filter-chips::state.showMoreLabel"
							data-wp-bind--hidden="woocommerce/product-filter-chips::state.isExpanded"
						>
							<?php
							/* translators: %d: number of hidden items */
							echo esc_html( sprintf( __( '+%d more', 'woocommerce' ), $hidden_count ) );
							?>
						</button>
					<?php endif; ?>
				</div>
			</fieldset>
		</div>
		<?php
		return ob_get_clean();
	}

	/**
	 * Get allowed HTML for item labels, including SVG for rating stars.
	 *
	 * @return array Allowed HTML elements and attributes.
	 */
	private function get_allowed_label_html() {
		return array_merge(
			wp_kses_allowed_html( 'post' ),
			array(
				'svg'  => array(
					'class'      => true,
					'xmlns'      => true,
					'width'      => true,
					'height'     => true,
					'viewbox'    => true,
					'fill'       => true,
					'aria-label' => true,
				),
				'path' => array(
					'd'            => true,
					'fill'         => true,
					'stroke'       => true,
					'stroke-width' => true,
					'transform'    => true,
				),
			)
		);
	}
}
