<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api;

use Automattic\WooCommerce\Api\Infrastructure\Principal;
use Automattic\WooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Authorization\ComposedAuthorizeQuery;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Authorization\MetadataAwareInternalQuery;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Authorization\MetadataAwareNoFlagQuery;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Inheritance\InheritedCapQuery;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Inheritance\InheritedPublicQuery;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Inheritance\MergedCapsQuery;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries\ComposedAuthorizeQuery as ComposedAuthorizeResolver;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries\InheritedCapQuery as InheritedCapResolver;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries\InheritedPublicQuery as InheritedPublicResolver;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries\MergedCapsQuery as MergedCapsResolver;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries\MetadataAwareInternalQuery as MetadataAwareInternalResolver;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries\MetadataAwareNoFlagQuery as MetadataAwareNoFlagResolver;
use WC_Unit_Test_Case;

/**
 * Tests for the dual `compute_preauthorized` paths:
 *
 *   1. The static helper emitted on each autogenerated resolver.
 *   2. The runtime `ResolverHelpers::compute_preauthorized()` helper that walks the
 *      command class's attributes via Reflection.
 *
 * Both paths must agree on every command — they implement the same
 * AND-of-attributes semantics, just at different stages of the build.
 *
 * Anonymous principals are represented by a {@see Principal} wrapping a
 * `WP_User` with `ID === 0`, mirroring what the controller passes through
 * the resolver context.
 */
class ComputePreauthorizedTest extends WC_Unit_Test_Case {
	/**
	 * Set up.
	 */
	public function setUp(): void {
		parent::setUp();
		wp_set_current_user( 0 );
	}

	/**
	 * Tear down.
	 */
	public function tearDown(): void {
		wp_set_current_user( 0 );
		parent::tearDown();
	}

	/**
	 * Build a {@see Principal} for the given role, or anonymous when null.
	 *
	 * @param ?string $role A WP role slug, or null to construct an anonymous principal.
	 */
	private function principal_with_role( ?string $role ): Principal {
		if ( null === $role ) {
			return new Principal( new \WP_User() );
		}
		$user = self::factory()->user->create_and_get( array( 'role' => $role ) );
		return new Principal( $user );
	}

	/**
	 * @testdox the autogen-emitted helper returns true for an admin on a single-cap command.
	 */
	public function test_autogen_helper_grants_for_admin_on_inherited_cap(): void {
		$admin     = $this->principal_with_role( 'administrator' );
		$rejected  = $this->principal_with_role( 'subscriber' );
		$anonymous = $this->principal_with_role( null );

		$this->assertTrue( InheritedCapResolver::compute_preauthorized( $admin ) );
		$this->assertFalse( InheritedCapResolver::compute_preauthorized( $rejected ) );
		$this->assertFalse( InheritedCapResolver::compute_preauthorized( $anonymous ) );
	}

	/**
	 * @testdox the autogen-emitted helper short-circuits to true for PublicAccess.
	 */
	public function test_autogen_helper_returns_true_for_public_access(): void {
		$this->assertTrue( InheritedPublicResolver::compute_preauthorized( $this->principal_with_role( null ) ) );
		$this->assertTrue( InheritedPublicResolver::compute_preauthorized( $this->principal_with_role( 'administrator' ) ) );
	}

	/**
	 * @testdox the autogen-emitted helper ANDs multiple inherited capabilities.
	 */
	public function test_autogen_helper_ands_merged_caps(): void {
		// The MergedCapsQuery requires manage_options AND edit_posts.
		// `editor` has edit_posts but not manage_options.
		$admin      = $this->principal_with_role( 'administrator' );
		$editor     = $this->principal_with_role( 'editor' );
		$subscriber = $this->principal_with_role( 'subscriber' );

		$this->assertTrue( MergedCapsResolver::compute_preauthorized( $admin ) );
		$this->assertFalse( MergedCapsResolver::compute_preauthorized( $editor ) );
		$this->assertFalse( MergedCapsResolver::compute_preauthorized( $subscriber ) );
	}

	/**
	 * @testdox ResolverHelpers::compute_preauthorized agrees with the autogen helper for inherited capabilities.
	 */
	public function test_utils_helper_matches_autogen_for_inherited_cap(): void {
		foreach ( array( 'administrator', 'subscriber', null ) as $role ) {
			$principal = $this->principal_with_role( $role );
			$autogen   = InheritedCapResolver::compute_preauthorized( $principal );
			$utils     = ResolverHelpers::compute_preauthorized( InheritedCapQuery::class, $principal );
			$this->assertSame(
				$autogen,
				$utils,
				'Drift between autogen and ResolverHelpers for InheritedCapQuery, role: ' . ( $role ?? '<anonymous>' )
			);
		}
	}

	/**
	 * @testdox ResolverHelpers::compute_preauthorized agrees with the autogen helper for PublicAccess.
	 */
	public function test_utils_helper_matches_autogen_for_public_access(): void {
		$anonymous = $this->principal_with_role( null );
		$this->assertTrue( ResolverHelpers::compute_preauthorized( InheritedPublicQuery::class, $anonymous ) );
		$this->assertSame(
			InheritedPublicResolver::compute_preauthorized( $anonymous ),
			ResolverHelpers::compute_preauthorized( InheritedPublicQuery::class, $anonymous )
		);
	}

	/**
	 * @testdox ResolverHelpers::compute_preauthorized agrees with the autogen helper for merged caps.
	 */
	public function test_utils_helper_matches_autogen_for_merged_caps(): void {
		foreach ( array( 'administrator', 'editor', null ) as $role ) {
			$principal = $this->principal_with_role( $role );
			$this->assertSame(
				MergedCapsResolver::compute_preauthorized( $principal ),
				ResolverHelpers::compute_preauthorized( MergedCapsQuery::class, $principal )
			);
		}
	}

	/**
	 * @testdox ResolverHelpers::compute_preauthorized works on a command with both attributes and authorize().
	 */
	public function test_utils_helper_for_command_with_attribute_and_authorize_method(): void {
		// ComposedAuthorizeQuery has both an attribute AND an authorize() method.
		// compute_preauthorized() answers the attribute-level question only.
		$admin = $this->principal_with_role( 'administrator' );

		$this->assertTrue( ComposedAuthorizeResolver::compute_preauthorized( $admin ) );
		$this->assertSame(
			ComposedAuthorizeResolver::compute_preauthorized( $admin ),
			ResolverHelpers::compute_preauthorized( ComposedAuthorizeQuery::class, $admin )
		);

		$anonymous = $this->principal_with_role( null );
		$this->assertFalse( ComposedAuthorizeResolver::compute_preauthorized( $anonymous ) );
		$this->assertSame(
			ComposedAuthorizeResolver::compute_preauthorized( $anonymous ),
			ResolverHelpers::compute_preauthorized( ComposedAuthorizeQuery::class, $anonymous )
		);
	}

	/**
	 * @testdox ResolverHelpers::compute_preauthorized rejects an unknown class.
	 */
	public function test_utils_helper_rejects_unknown_class(): void {
		$this->expectException( \InvalidArgumentException::class );
		ResolverHelpers::compute_preauthorized( '\\Definitely\\Not\\A\\Class', $this->principal_with_role( null ) );
	}

	/**
	 * @testdox the autogen-emitted helper threads the class's #[Metadata] entries into $_metadata.
	 */
	public function test_autogen_helper_threads_metadata_slot(): void {
		$principal = $this->principal_with_role( 'administrator' );

		// The RequiresInternalFlag attribute grants only when $_metadata['query']['internal'] === true.
		$this->assertTrue(
			MetadataAwareInternalResolver::compute_preauthorized( $principal ),
			'#[Internal] metadata should reach the attribute via $_metadata.'
		);
		$this->assertFalse(
			MetadataAwareNoFlagResolver::compute_preauthorized( $principal ),
			'A command with no #[Internal] should produce an empty `query` slice and deny.'
		);
	}

	/**
	 * @testdox ResolverHelpers::compute_preauthorized threads $_metadata to agree with the autogen helper.
	 */
	public function test_utils_helper_threads_metadata_slot(): void {
		$principal = $this->principal_with_role( 'administrator' );

		$this->assertSame(
			MetadataAwareInternalResolver::compute_preauthorized( $principal ),
			ResolverHelpers::compute_preauthorized( MetadataAwareInternalQuery::class, $principal )
		);
		$this->assertSame(
			MetadataAwareNoFlagResolver::compute_preauthorized( $principal ),
			ResolverHelpers::compute_preauthorized( MetadataAwareNoFlagQuery::class, $principal )
		);
	}
}
