<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api;

use Automattic\WooCommerce\Api\Infrastructure\GraphQLControllerBase;
use Automattic\WooCommerce\Internal\Api\QueryCache;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\CountingNodeList;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Infrastructure\ClassResolver as DummyContainer;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Store as DummyStore;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLController as DummyGraphQLController;
use Automattic\WooCommerce\Vendor\GraphQL\Language\AST\DocumentNode;
use Automattic\WooCommerce\Vendor\GraphQL\Language\Parser;
use WC_REST_Unit_Test_Case;

/**
 * End-to-end tests for {@see GraphQLControllerBase}, executing real requests
 * through a controller wired to the dummy fixture API.
 *
 * Covers the rules the controller enforces beyond what the schema itself
 * checks: depth limit, complexity limit, introspection gating, error
 * formatting, GET / POST routing, mutation rejection over GET, JSON
 * decoding of variables / extensions, and APQ.
 */
class GraphQLControllerExecutionTest extends WC_REST_Unit_Test_Case {
	/**
	 * The system under test.
	 *
	 * @var GraphQLControllerBase
	 */
	private GraphQLControllerBase $sut;

	/**
	 * Set up.
	 */
	public function setUp(): void {
		parent::setUp();
		wp_cache_flush();
		DummyStore::reset();
		DummyContainer::reset();
		wp_set_current_user( 0 );

		$this->sut = new DummyGraphQLController();
		$this->sut->init( new QueryCache() );
	}

	/**
	 * Tear down.
	 */
	public function tearDown(): void {
		DummyStore::reset();
		DummyContainer::reset();
		wp_set_current_user( 0 );
		wp_cache_flush();
		parent::tearDown();
	}

	/**
	 * Build a POST WP_REST_Request with JSON-style body params.
	 *
	 * @param array $body The decoded request body.
	 */
	private function post_request( array $body ): \WP_REST_Request {
		$request = new \WP_REST_Request( 'POST', '/wc/graphql' );
		foreach ( $body as $key => $value ) {
			$request->set_param( $key, $value );
		}
		return $request;
	}

	/**
	 * Build a GET WP_REST_Request with query-string params.
	 *
	 * @param array $params The query-string parameters.
	 */
	private function get_request( array $params ): \WP_REST_Request {
		$request = new \WP_REST_Request( 'GET', '/wc/graphql' );
		foreach ( $params as $key => $value ) {
			$request->set_param( $key, $value );
		}
		return $request;
	}

	/**
	 * @testdox handle_request returns 200 + data for a successful query.
	 */
	public function test_handle_request_returns_200_for_successful_query(): void {
		$response = $this->sut->handle_request( $this->post_request( array( 'query' => '{ greeting { result } }' ) ) );

		$this->assertSame( 200, $response->get_status() );
		$data = $response->get_data();
		$this->assertSame( 'Hello, world!', $data['data']['greeting']['result'] ?? null );
	}

	/**
	 * @testdox handle_request decodes JSON-encoded variables on GET requests.
	 */
	public function test_handle_request_decodes_get_variables_json(): void {
		$response = $this->sut->handle_request(
			$this->get_request(
				array(
					'query'     => 'query Q($who: String) { greeting(name: $who) { result } }',
					'variables' => '{"who":"Bob"}',
				)
			)
		);

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'Hello, Bob!', $response->get_data()['data']['greeting']['result'] ?? null );
	}

	/**
	 * @testdox handle_request rejects malformed variables JSON with INVALID_ARGUMENT.
	 */
	public function test_handle_request_rejects_malformed_variables_json(): void {
		$response = $this->sut->handle_request(
			$this->get_request(
				array(
					'query'     => '{ greeting { result } }',
					'variables' => 'not-json',
				)
			)
		);

		$this->assertSame( 400, $response->get_status() );
		$data = $response->get_data();
		$this->assertSame( 'INVALID_ARGUMENT', $data['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request rejects non-object variables with INVALID_ARGUMENT.
	 */
	public function test_handle_request_rejects_scalar_variables(): void {
		$response = $this->sut->handle_request(
			$this->get_request(
				array(
					'query'     => '{ greeting { result } }',
					'variables' => '"a string"',
				)
			)
		);

		$this->assertSame( 400, $response->get_status() );
		$this->assertSame( 'INVALID_ARGUMENT', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request rejects mutations over GET with METHOD_NOT_ALLOWED.
	 */
	public function test_handle_request_rejects_mutation_over_get(): void {
		$response = $this->sut->handle_request(
			$this->get_request( array( 'query' => 'mutation { increment(value: 1) { result } }' ) )
		);

		$this->assertSame( 405, $response->get_status() );
		$this->assertSame( 'METHOD_NOT_ALLOWED', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request maps an authenticated-but-denied authorization to HTTP 403.
	 */
	public function test_handle_request_maps_authorization_failure_to_403(): void {
		// `widget` requires manage_options. An editor is authenticated but lacks the
		// cap → attribute denies → FORBIDDEN/403 (the caller is recognised; re-auth
		// won't help).
		$editor = self::factory()->user->create( array( 'role' => 'editor' ) );
		wp_set_current_user( $editor );

		$response = $this->sut->handle_request( $this->post_request( array( 'query' => '{ widget(id: 1) { id } }' ) ) );

		$this->assertSame( 403, $response->get_status() );
		$this->assertSame( 'FORBIDDEN', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request maps an anonymous-rejected authorization to HTTP 401.
	 */
	public function test_handle_request_maps_anonymous_authorization_failure_to_401(): void {
		// `widget` requires manage_options. Anonymous caller → attribute denies but
		// the principal isn't authenticated → UNAUTHORIZED/401 (re-auth might help).
		wp_set_current_user( 0 );

		$response = $this->sut->handle_request( $this->post_request( array( 'query' => '{ widget(id: 1) { id } }' ) ) );

		$this->assertSame( 401, $response->get_status() );
		$this->assertSame( 'UNAUTHORIZED', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request rejects queries that exceed the configured depth limit.
	 */
	public function test_handle_request_rejects_excessive_depth(): void {
		// DEFAULT_MAX_QUERY_DEPTH is 15. Build a deeply nested query well past that.
		$inner = 'id';
		for ( $i = 0; $i < 20; $i++ ) {
			$inner = "reviews { nodes { $inner } }";
		}
		$query = "{ widget(id: 1) { $inner } }";

		$response = $this->sut->handle_request( $this->post_request( array( 'query' => $query ) ) );

		$this->assertSame( 400, $response->get_status() );
		$this->assertNotEmpty( $response->get_data()['errors'] ?? array() );
	}

	/**
	 * @testdox handle_request rejects queries that exceed the configured complexity limit.
	 */
	public function test_handle_request_rejects_excessive_complexity(): void {
		// Complexity for the widgets connection field with first=100 and a
		// child of complexity ≥ 11 will exceed DEFAULT_MAX_QUERY_COMPLEXITY (1000).
		$query = '{
			widgets(first: 100) {
				nodes {
					reviews(first: 100) {
						nodes { id body score }
					}
				}
			}
		}';

		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$response = $this->sut->handle_request( $this->post_request( array( 'query' => $query ) ) );

		$this->assertSame( 400, $response->get_status() );
		$this->assertNotEmpty( $response->get_data()['errors'] ?? array() );
	}

	/**
	 * Build a document in which each named fragment spreads the next one twice,
	 * so the number of spreads reachable from the root doubles with every fragment.
	 *
	 * @param int    $fragment_count Number of chained fragments.
	 * @param string $type_name      Type condition of the fragments.
	 * @param string $root           Selection set body of the operation (must spread F0).
	 * @param string $leaf           Selection set body of the last fragment.
	 */
	private function build_duplicate_spread_chain( int $fragment_count, string $type_name, string $root, string $leaf ): string {
		$document = "query Q { {$root} }\n";
		for ( $i = 0; $i < $fragment_count - 1; $i++ ) {
			$next      = $i + 1;
			$document .= "fragment F{$i} on {$type_name} { ...F{$next} ...F{$next} }\n";
		}
		$last = $fragment_count - 1;

		return $document . "fragment F{$last} on {$type_name} { {$leaf} }\n";
	}

	/**
	 * Upper bound on how many times the request pipeline (validation rules,
	 * executor, query info extraction) may iterate one fragment's selections:
	 * a handful of passes that each visit a fragment once (4 when validation
	 * rejects the document and 6 when it executes, at the time of writing),
	 * as opposed to once per spread.
	 */
	private const MAX_ITERATIONS_PER_FRAGMENT = 32;

	/**
	 * Make the controller process a pre-parsed document whose fragment
	 * selection sets count how often they are iterated.
	 *
	 * Injected through a QueryCache double so the AST reaches the controller
	 * as-is (the real cache would re-parse the query string). Resets the
	 * iteration counter.
	 *
	 * @param string $query The GraphQL document.
	 * @return int The number of fragments in the document.
	 */
	private function inject_counting_document( string $query ): int {
		$document       = Parser::parse( $query, array( 'noLocation' => true ) );
		$fragment_count = CountingNodeList::instrument_fragments( $document );
		CountingNodeList::reset();

		$cache = new class( $document ) extends QueryCache {
			/**
			 * Constructor.
			 *
			 * @param DocumentNode $document The document to hand to the controller.
			 */
			public function __construct( private DocumentNode $document ) {}

			/**
			 * Return the injected document regardless of the request.
			 *
			 * @param ?string $query      Ignored.
			 * @param array   $extensions Ignored.
			 */
			public function resolve( ?string $query, array $extensions ): DocumentNode {
				unset( $query, $extensions );
				return $this->document;
			}
		};
		$this->sut->init( $cache );

		return $fragment_count;
	}

	/**
	 * @testdox handle_request rejects a document whose fragments spread each other twice, visiting each fragment a bounded number of times.
	 */
	public function test_handle_request_rejects_duplicate_spread_document_with_bounded_work(): void {
		$query          = $this->build_duplicate_spread_chain( 24, 'Query', '...F0', '__typename' );
		$fragment_count = $this->inject_counting_document( $query );

		$response = $this->sut->handle_request( $this->post_request( array( 'query' => $query ) ) );

		$this->assertSame( 400, $response->get_status() );
		$this->assertSame( 'Maximum query complexity exceeded.', $response->get_data()['errors'][0]['message'] ?? null );
		$this->assertLessThanOrEqual( self::MAX_ITERATIONS_PER_FRAGMENT * $fragment_count, CountingNodeList::$iterations );
	}

	/**
	 * @testdox handle_request executes a zero-complexity document whose fragments spread each other twice, visiting each fragment a bounded number of times in the resolvers.
	 */
	public function test_handle_request_executes_zero_complexity_duplicate_spread_document_with_bounded_work(): void {
		// `first: 0` keeps the score within the limit, so the document reaches
		// the resolver and its QueryInfoExtractor call, which must also expand
		// each fragment only once.
		$query          = $this->build_duplicate_spread_chain( 24, 'WidgetConnection', 'widgets(first: 0) { ...F0 }', '__typename' );
		$fragment_count = $this->inject_counting_document( $query );

		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$response = $this->sut->handle_request( $this->post_request( array( 'query' => $query ) ) );

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'WidgetConnection', $response->get_data()['data']['widgets']['__typename'] ?? null );
		$this->assertLessThanOrEqual( self::MAX_ITERATIONS_PER_FRAGMENT * $fragment_count, CountingNodeList::$iterations );
	}

	/**
	 * @testdox handle_request blocks introspection for low-privilege callers.
	 */
	public function test_handle_request_blocks_introspection_for_unauthorized_users(): void {
		wp_set_current_user( 0 );

		$response = $this->sut->handle_request(
			$this->post_request( array( 'query' => '{ __schema { queryType { name } } }' ) )
		);

		$data = $response->get_data();
		// Either errors out or returns no data — depending on validation rule.
		$this->assertNotEmpty( $data['errors'] ?? array() );
	}

	/**
	 * @testdox handle_request allows introspection for users with manage_woocommerce.
	 */
	public function test_handle_request_allows_introspection_for_admins(): void {
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$response = $this->sut->handle_request(
			$this->post_request( array( 'query' => '{ __schema { queryType { name } } }' ) )
		);

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'Query', $response->get_data()['data']['__schema']['queryType']['name'] ?? null );
	}

	/**
	 * @testdox the woocommerce_graphql_can_introspect filter can grant introspection to an anonymous request.
	 */
	public function test_filter_can_grant_introspection_to_anonymous_user(): void {
		wp_set_current_user( 0 );

		$received_principal = null;
		$received_request   = null;
		$filter             = function ( bool $can_introspect, ?object $principal, \WP_REST_Request $request ) use ( &$received_principal, &$received_request ): bool {
			$received_principal = $principal;
			$received_request   = $request;
			return true;
		};
		add_filter( 'woocommerce_graphql_can_introspect', $filter, 10, 3 );

		try {
			$response = $this->sut->handle_request(
				$this->post_request( array( 'query' => '{ __schema { queryType { name } } }' ) )
			);
		} finally {
			remove_filter( 'woocommerce_graphql_can_introspect', $filter, 10 );
		}

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'Query', $response->get_data()['data']['__schema']['queryType']['name'] ?? null );

		$this->assertNotNull( $received_principal, 'The filter should receive the resolved principal even for anonymous requests.' );
		$this->assertInstanceOf( \WP_REST_Request::class, $received_request );
	}

	/**
	 * @testdox the woocommerce_graphql_can_introspect filter can revoke introspection from an admin.
	 */
	public function test_filter_can_revoke_introspection_from_admin(): void {
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$filter = function (): bool {
			return false;
		};
		add_filter( 'woocommerce_graphql_can_introspect', $filter );

		try {
			$response = $this->sut->handle_request(
				$this->post_request( array( 'query' => '{ __schema { queryType { name } } }' ) )
			);
		} finally {
			remove_filter( 'woocommerce_graphql_can_introspect', $filter );
		}

		$data = $response->get_data();
		$this->assertNotEmpty( $data['errors'] ?? array() );
	}

	/**
	 * @testdox the woocommerce_graphql_can_introspect filter must return strictly true; truthy non-bool denies.
	 */
	public function test_filter_requires_strict_true_to_grant_introspection(): void {
		wp_set_current_user( 0 );

		$filter = function () {
			return 1;
		};
		add_filter( 'woocommerce_graphql_can_introspect', $filter );

		try {
			$response = $this->sut->handle_request(
				$this->post_request( array( 'query' => '{ __schema { queryType { name } } }' ) )
			);
		} finally {
			remove_filter( 'woocommerce_graphql_can_introspect', $filter );
		}

		$data = $response->get_data();
		$this->assertNotEmpty( $data['errors'] ?? array() );
	}

	/**
	 * @testdox handle_request returns a syntax error as HTTP 400 GRAPHQL_PARSE_ERROR.
	 */
	public function test_handle_request_handles_syntax_error(): void {
		$response = $this->sut->handle_request( $this->post_request( array( 'query' => '{ widget(id:' ) ) );

		$this->assertSame( 400, $response->get_status() );
		$this->assertSame( 'GRAPHQL_PARSE_ERROR', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request returns BAD_REQUEST when the request has no query and no APQ.
	 */
	public function test_handle_request_rejects_missing_query(): void {
		$response = $this->sut->handle_request( $this->post_request( array() ) );

		$this->assertSame( 400, $response->get_status() );
		$this->assertSame( 'BAD_REQUEST', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request executes a previously-registered APQ via hash-only follow-up.
	 */
	public function test_handle_request_apq_round_trip(): void {
		$query = '{ greeting { result } }';
		$hash  = hash( 'sha256', $query );

		$register = $this->sut->handle_request(
			$this->post_request(
				array(
					'query'      => $query,
					'extensions' => array(
						'persistedQuery' => array(
							'version'    => 1,
							'sha256Hash' => $hash,
						),
					),
				)
			)
		);
		$this->assertSame( 200, $register->get_status() );

		$followup = $this->sut->handle_request(
			$this->post_request(
				array(
					'extensions' => array(
						'persistedQuery' => array(
							'version'    => 1,
							'sha256Hash' => $hash,
						),
					),
				)
			)
		);

		$this->assertSame( 200, $followup->get_status() );
		$this->assertSame( 'Hello, world!', $followup->get_data()['data']['greeting']['result'] ?? null );
	}

	/**
	 * @testdox handle_request returns PERSISTED_QUERY_NOT_FOUND on HTTP 200 for unknown hashes.
	 */
	public function test_handle_request_apq_unknown_hash_returns_200(): void {
		$response = $this->sut->handle_request(
			$this->post_request(
				array(
					'extensions' => array(
						'persistedQuery' => array(
							'version'    => 1,
							'sha256Hash' => str_repeat( '0', 64 ),
						),
					),
				)
			)
		);

		// APQ hash misses are intentionally HTTP 200 per the Apollo protocol.
		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'PERSISTED_QUERY_NOT_FOUND', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request falls back to HTTP 500 for resolver errors with no entry in the controller's status map.
	 */
	public function test_handle_request_translates_failing_query_errors(): void {
		$response = $this->sut->handle_request(
			$this->post_request( array( 'query' => '{ failing(kind: "api_exception") { result } }' ) )
		);

		// CUSTOM_FAILURE has no entry in the controller's status map, so it
		// falls back to 500.
		$this->assertSame( 500, $response->get_status() );
		$this->assertSame( 'CUSTOM_FAILURE', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request honours operationName when deciding whether to reject a mutation over GET.
	 */
	public function test_handle_request_uses_operation_name_for_mutation_check(): void {
		$multi_op = 'query GetIt { greeting { result } } mutation DoIt { increment(value: 1) { result } }';

		// Picking the query operation must NOT trip the mutation-over-GET guard.
		$query_response = $this->sut->handle_request(
			$this->get_request(
				array(
					'query'         => $multi_op,
					'operationName' => 'GetIt',
				)
			)
		);
		$this->assertSame( 200, $query_response->get_status() );
		$this->assertSame( 'Hello, world!', $query_response->get_data()['data']['greeting']['result'] ?? null );

		// Picking the mutation operation in the same document MUST be rejected.
		$mutation_response = $this->sut->handle_request(
			$this->get_request(
				array(
					'query'         => $multi_op,
					'operationName' => 'DoIt',
				)
			)
		);
		$this->assertSame( 405, $mutation_response->get_status() );
		$this->assertSame(
			'METHOD_NOT_ALLOWED',
			$mutation_response->get_data()['errors'][0]['extensions']['code'] ?? null
		);
	}

	/**
	 * @testdox a wrong-type field argument is rejected as BAD_USER_INPUT (HTTP 400).
	 */
	public function test_handle_request_field_arg_type_mismatch_is_bad_user_input(): void {
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$response = $this->sut->handle_request(
			$this->post_request( array( 'query' => '{ widget(id: "not-an-int") { id } }' ) )
		);

		$this->assertSame( 400, $response->get_status() );
		$this->assertSame( 'BAD_USER_INPUT', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox a missing required field argument is rejected as BAD_USER_INPUT (HTTP 400).
	 */
	public function test_handle_request_missing_required_arg_is_bad_user_input(): void {
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$response = $this->sut->handle_request(
			$this->post_request( array( 'query' => '{ widget { id } }' ) )
		);

		$this->assertSame( 400, $response->get_status() );
		$this->assertSame( 'BAD_USER_INPUT', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox a variable whose value doesn't match its declared type is rejected as BAD_USER_INPUT.
	 */
	public function test_handle_request_variable_type_mismatch_is_bad_user_input(): void {
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$response = $this->sut->handle_request(
			$this->post_request(
				array(
					'query'     => 'query Q($id: Int!) { widget(id: $id) { id } }',
					'variables' => array( 'id' => 'not-an-int' ),
				)
			)
		);

		$this->assertSame( 400, $response->get_status() );
		$this->assertSame( 'BAD_USER_INPUT', $response->get_data()['errors'][0]['extensions']['code'] ?? null );
	}

	/**
	 * @testdox handle_request resolves the request principal eagerly and threads it into resolvers.
	 *
	 * The dummy fixture's principalAware query echoes the principal user_login.
	 * Because no PrincipalResolver convention class is shipped under the fixture,
	 * the controller falls back to a {@see \Automattic\WooCommerce\Api\Infrastructure\Principal}
	 * wrapping `wp_get_current_user()` — the same default WC core's own endpoint uses.
	 */
	public function test_handle_request_threads_principal_into_resolver(): void {
		$user_id = self::factory()->user->create(
			array(
				'user_login' => 'carol',
				'role'       => 'subscriber',
			)
		);
		wp_set_current_user( $user_id );

		$response = $this->sut->handle_request(
			$this->post_request( array( 'query' => '{ principalAware { result } }' ) )
		);

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'carol', $response->get_data()['data']['principalAware']['result'] ?? null );
	}

	/**
	 * @testdox handle_request threads an anonymous-marker principal for unauthenticated requests.
	 */
	public function test_handle_request_threads_anonymous_principal(): void {
		wp_set_current_user( 0 );

		$response = $this->sut->handle_request(
			$this->post_request( array( 'query' => '{ principalAware { result } }' ) )
		);

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'anonymous', $response->get_data()['data']['principalAware']['result'] ?? null );
	}

	/**
	 * @testdox a throw from the woocommerce_graphql_can_introspect filter callback denies introspection (fail-closed).
	 */
	public function test_filter_callback_throw_denies_introspection(): void {
		$admin = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $admin );

		$filter = function () {
			throw new \RuntimeException( 'broken-filter-callback' );
		};
		add_filter( 'woocommerce_graphql_can_introspect', $filter );

		try {
			$response = $this->sut->handle_request(
				$this->post_request( array( 'query' => '{ __schema { queryType { name } } }' ) )
			);
		} finally {
			remove_filter( 'woocommerce_graphql_can_introspect', $filter );
		}

		// Validation rejects the introspection query (fail-closed), and the
		// filter's exception message must not appear anywhere on the wire.
		$data = $response->get_data();
		$this->assertNotEmpty( $data['errors'] ?? array() );

		$wire = wp_json_encode( $data );
		$this->assertIsString( $wire );
		$this->assertStringNotContainsString( 'broken-filter-callback', $wire );
	}

	/**
	 * @testdox a null principal denies introspection even when a permissive filter is installed.
	 */
	public function test_null_principal_denies_introspection_even_with_permissive_filter(): void {
		$filter_invoked = false;
		$filter         = function ( bool $can_introspect ) use ( &$filter_invoked ): bool {
			// Avoid parameter not used PHPCS errors.
			unset( $can_introspect );
			$filter_invoked = true;
			return true;
		};
		add_filter( 'woocommerce_graphql_can_introspect', $filter );

		try {
			$reflection = new \ReflectionClass( GraphQLControllerBase::class );
			$method     = $reflection->getMethod( 'is_introspection_allowed' );
			$method->setAccessible( true );

			$request = new \WP_REST_Request( 'POST', '/wc/graphql' );
			$result  = $method->invoke( $this->sut, null, $request );
		} finally {
			remove_filter( 'woocommerce_graphql_can_introspect', $filter );
		}

		$this->assertFalse( $result );
		$this->assertFalse( $filter_invoked, 'Filter must not be consulted for null principals.' );
	}

	/**
	 * @testdox a throw from the principal's can_introspect() method denies introspection (fail-closed).
	 */
	public function test_principal_method_throw_denies_introspection(): void {
		$throwing_principal = new class() {
			/**
			 * Always throw to simulate a buggy plugin principal.
			 *
			 * @throws \RuntimeException Always.
			 */
			public function can_introspect(): bool {
				throw new \RuntimeException( 'broken-principal-method' );
			}
		};

		$reflection = new \ReflectionClass( GraphQLControllerBase::class );
		$method     = $reflection->getMethod( 'is_introspection_allowed' );
		$method->setAccessible( true );

		$request = new \WP_REST_Request( 'POST', '/wc/graphql' );
		$this->assertFalse( $method->invoke( $this->sut, $throwing_principal, $request ) );
	}
}
