<?php
declare( strict_types = 1 );

namespace Automattic\WooCommerce\Tests\Internal\Api;

use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLController as AutogeneratedGraphQLController;
use Automattic\WooCommerce\Api\Infrastructure\GraphQLControllerBase;
use Automattic\WooCommerce\Api\Infrastructure\Main;
use WC_REST_Unit_Test_Case;

/**
 * Tests for the GraphQLControllerBase class — specifically the HTTP methods
 * registered on the /wc/graphql route based on the GET endpoint option.
 */
class GraphQLControllerTest extends WC_REST_Unit_Test_Case {
	/**
	 * The System Under Test.
	 *
	 * @var GraphQLControllerBase
	 */
	private $sut;

	/**
	 * Set up before each test.
	 *
	 * Skips on PHP < 8.1 because GraphQLControllerBase uses PHP 8.0+ syntax in its
	 * source file (named arguments). In production the class is only loaded
	 * after {@see Main::is_enabled()} gates on PHP 8.1+; these tests bypass
	 * that gate by hitting the DI container directly, so we replicate it here.
	 */
	public function setUp(): void {
		parent::setUp();

		if ( PHP_VERSION_ID < 80100 ) {
			$this->markTestSkipped( 'GraphQLControllerBase requires PHP 8.1+.' );
		}

		// GraphQLControllerBase is abstract; instantiate the autogenerated subclass
		// that wc_get_container() also uses via Main::handle_rest_api_init_for_core().
		$this->sut = wc_get_container()->get( AutogeneratedGraphQLController::class );
	}

	/**
	 * Clean up GraphQL options between tests.
	 */
	public function tearDown(): void {
		delete_option( Main::OPTION_GET_ENDPOINT_ENABLED );
		delete_option( Main::OPTION_ENDPOINT_URL );
		delete_option( Main::OPTION_MAX_QUERY_DEPTH );
		delete_option( Main::OPTION_MAX_QUERY_COMPLEXITY );
		parent::tearDown();
	}

	/**
	 * @testdox register exposes POST only when the GET endpoint option is disabled.
	 */
	public function test_register_exposes_post_only_when_get_disabled(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'no' );

		$this->sut->register();

		$handlers = rest_get_server()->get_routes()['/wc/graphql'];
		$this->assertCount( 1, $handlers, 'Exactly one handler should be registered for /wc/graphql.' );
		$methods = $handlers[0]['methods'];
		$this->assertTrue( $methods['POST'] ?? false );
		$this->assertFalse( $methods['GET'] ?? false );
	}

	/**
	 * @testdox register exposes GET and POST when the GET endpoint option is enabled.
	 */
	public function test_register_exposes_get_and_post_when_get_enabled(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'yes' );

		$this->sut->register();

		$handlers = rest_get_server()->get_routes()['/wc/graphql'];
		$this->assertCount( 1, $handlers, 'Exactly one handler should be registered for /wc/graphql.' );
		$methods = $handlers[0]['methods'];
		$this->assertTrue( $methods['GET'] ?? false );
		$this->assertTrue( $methods['POST'] ?? false );
	}

	/**
	 * @testdox get_endpoint_url returns the default when the option is unset.
	 */
	public function test_get_endpoint_url_returns_default_when_option_unset(): void {
		delete_option( Main::OPTION_ENDPOINT_URL );
		$this->assertSame( GraphQLControllerBase::DEFAULT_ENDPOINT_URL, GraphQLControllerBase::get_endpoint_url() );
	}

	/**
	 * @testdox get_endpoint_url returns the stored option value when it is well-formed.
	 */
	public function test_get_endpoint_url_returns_option_value_when_valid(): void {
		update_option( Main::OPTION_ENDPOINT_URL, 'wc/v4/graphql' );
		$this->assertSame( 'wc/v4/graphql', GraphQLControllerBase::get_endpoint_url() );
	}

	/**
	 * @testdox get_endpoint_url strips surrounding slashes from the stored option.
	 */
	public function test_get_endpoint_url_strips_surrounding_slashes(): void {
		update_option( Main::OPTION_ENDPOINT_URL, '/wc/v4/graphql/' );
		$this->assertSame( 'wc/v4/graphql', GraphQLControllerBase::get_endpoint_url() );
	}

	/**
	 * @testdox get_endpoint_url falls back to the default when the option has fewer than two segments.
	 * @dataProvider provider_invalid_endpoint_url_values
	 *
	 * @param string $value The invalid option value.
	 */
	public function test_get_endpoint_url_falls_back_on_invalid( string $value ): void {
		update_option( Main::OPTION_ENDPOINT_URL, $value );
		$this->assertSame( GraphQLControllerBase::DEFAULT_ENDPOINT_URL, GraphQLControllerBase::get_endpoint_url() );
	}

	/**
	 * @testdox register uses the configured endpoint URL when the option is set.
	 */
	public function test_register_uses_configured_endpoint_url(): void {
		update_option( Main::OPTION_ENDPOINT_URL, 'wc/v4/graphql' );

		$this->sut->register();

		$routes = rest_get_server()->get_routes();
		$this->assertArrayHasKey( '/wc/v4/graphql', $routes, 'The configured endpoint URL should be registered.' );
		$this->assertArrayNotHasKey( '/wc/graphql', $routes, 'The default endpoint URL should not be registered when a custom one is set.' );
	}

	/**
	 * Invalid values that the getter should replace with the default.
	 *
	 * @return array<string, array{string}>
	 */
	public function provider_invalid_endpoint_url_values(): array {
		return array(
			'empty string'         => array( '' ),
			'slashes only'         => array( '///' ),
			'single segment'       => array( 'graphql' ),
			'empty middle segment' => array( 'wc//graphql' ),
			'invalid character'    => array( 'wc/graph*ql' ),
			'space in segment'     => array( 'wc/my graphql' ),
		);
	}

	/**
	 * @testdox get_max_query_depth returns the default when the option is unset.
	 */
	public function test_get_max_query_depth_returns_default_when_option_unset(): void {
		delete_option( Main::OPTION_MAX_QUERY_DEPTH );
		$this->assertSame(
			GraphQLControllerBase::DEFAULT_MAX_QUERY_DEPTH,
			GraphQLControllerBase::get_max_query_depth()
		);
	}

	/**
	 * @testdox get_max_query_depth returns the option value when it is a positive integer.
	 */
	public function test_get_max_query_depth_returns_option_value_when_positive(): void {
		update_option( Main::OPTION_MAX_QUERY_DEPTH, '7' );
		$this->assertSame( 7, GraphQLControllerBase::get_max_query_depth() );
	}

	/**
	 * @testdox get_max_query_depth falls back to the default when the option is empty, zero, or negative.
	 * @dataProvider provider_non_positive_option_values
	 *
	 * @param string $value The non-positive option value.
	 */
	public function test_get_max_query_depth_falls_back_on_non_positive( string $value ): void {
		update_option( Main::OPTION_MAX_QUERY_DEPTH, $value );
		$this->assertSame(
			GraphQLControllerBase::DEFAULT_MAX_QUERY_DEPTH,
			GraphQLControllerBase::get_max_query_depth()
		);
	}

	/**
	 * @testdox get_max_query_complexity returns the default when the option is unset.
	 */
	public function test_get_max_query_complexity_returns_default_when_option_unset(): void {
		delete_option( Main::OPTION_MAX_QUERY_COMPLEXITY );
		$this->assertSame(
			GraphQLControllerBase::DEFAULT_MAX_QUERY_COMPLEXITY,
			GraphQLControllerBase::get_max_query_complexity()
		);
	}

	/**
	 * @testdox get_max_query_complexity returns the option value when it is a positive integer.
	 */
	public function test_get_max_query_complexity_returns_option_value_when_positive(): void {
		update_option( Main::OPTION_MAX_QUERY_COMPLEXITY, '500' );
		$this->assertSame( 500, GraphQLControllerBase::get_max_query_complexity() );
	}

	/**
	 * @testdox get_max_query_complexity falls back to the default when the option is empty, zero, or negative.
	 * @dataProvider provider_non_positive_option_values
	 *
	 * @param string $value The non-positive option value.
	 */
	public function test_get_max_query_complexity_falls_back_on_non_positive( string $value ): void {
		update_option( Main::OPTION_MAX_QUERY_COMPLEXITY, $value );
		$this->assertSame(
			GraphQLControllerBase::DEFAULT_MAX_QUERY_COMPLEXITY,
			GraphQLControllerBase::get_max_query_complexity()
		);
	}

	/**
	 * Non-positive values that the getters should replace with the default.
	 *
	 * @return array<string, array{string}>
	 */
	public function provider_non_positive_option_values(): array {
		return array(
			'empty string' => array( '' ),
			'zero'         => array( '0' ),
			'negative'     => array( '-5' ),
		);
	}
}
