<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Internal\Api\Schema;

/**
 * Stable subclass of the webonyx EnumType used by autogenerated enums.
 *
 * The constructor accepts the same associative-array config webonyx
 * documents (keys: `name`, `description`, `values`).
 *
 * A `metadata` config key may also be provided; see
 * {@see ObjectType::get_metadata()} for the semantics.
 *
 * @internal Reserved for autogenerated resolver code.
 */
class EnumType extends \Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\EnumType {
	/**
	 * Type-level metadata entries declared in the config, keyed by name.
	 *
	 * @return array<string, bool|int|float|string|null>
	 */
	public function get_metadata(): array {
		return $this->config['metadata'] ?? array();
	}
}
