<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Internal\Api\Schema;

/**
 * Stable subclass of the webonyx EnumType used by autogenerated enums.
 *
 * The constructor accepts the same associative-array config webonyx
 * documents (keys: `name`, `description`, `values`).
 *
 * @internal Reserved for autogenerated resolver code.
 */
class EnumType extends \Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\EnumType {
}
