<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Internal\Api\Schema;

use Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\Type as WebonyxType;

/**
 * Static facade for GraphQL scalar types and type modifiers referenced by
 * autogenerated resolvers.
 *
 * Autogenerated code emitted by ApiBuilder only touches webonyx through
 * this (and the other classes in the Internal\Api\Schema namespace), so
 * the underlying GraphQL engine can be swapped without invalidating
 * already-committed generated code. Return types are intentionally
 * omitted so a future migration can change the concrete return type
 * without breaking callers.
 *
 * @internal Reserved for autogenerated resolver code.
 */
final class Type {
	public static function int() {
		return WebonyxType::int();
	}

	public static function string() {
		return WebonyxType::string();
	}

	public static function boolean() {
		return WebonyxType::boolean();
	}

	public static function float() {
		return WebonyxType::float();
	}

	public static function id() {
		return WebonyxType::id();
	}

	/**
	 * @param mixed $inner A nullable schema type.
	 */
	public static function nonNull( $inner ) {
		return WebonyxType::nonNull( $inner );
	}

	/**
	 * @param mixed $inner A schema type.
	 */
	public static function listOf( $inner ) {
		return WebonyxType::listOf( $inner );
	}
}
