<?php

declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Pagination;

use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\ProductVariation as ProductVariationType;
use Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\ObjectType;
use Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\Type;

class ProductVariationEdge {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'   => 'ProductVariationEdge',
					'fields' => fn() => array(
						'cursor' => array(
							'type' => Type::nonNull( Type::string() ),
						),
						'node'   => array(
							'type' => Type::nonNull( ProductVariationType::get() ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
