<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Api\Utils;

use Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\EnumType;
use Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\HasFieldsType;
use Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\InputObjectType;
use Automattic\WooCommerce\Vendor\GraphQL\Type\Definition\Type;

/**
 * Opaque handle to a dual-API GraphQL schema, exposing the runtime inspection
 * operations the dual-API surface supports.
 *
 * The handle wraps the live engine schema but does not expose it. Clients
 * therefore depend only on the methods this class declares — never on the
 * underlying engine type — which keeps a future engine swap as a non-public
 * API change.
 *
 * Construction is reserved for the dual-API infrastructure. Obtain a handle
 * via your dual-API `GraphQLController`'s `get_schema()` method:
 *
 *     $schema = wc_get_container()
 *         ->get( \Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLController::class )
 *         ->get_schema();
 *
 * WooCommerce plugins implementing their own dual API reach a handle through
 * their own concrete autogenerated controller the same way.
 *
 * The current public surface is the metadata channel: {@see self::get_all_metadata()}
 * returns every metadata row in the schema, {@see self::find_metadata()} applies
 * filter-narrows semantics over the same set.
 *
 * @phpstan-type MetadataRow array{
 *     type: string,
 *     field: ?string,
 *     argument: ?string,
 *     enumValue: ?string,
 *     entries: array<string, bool|int|float|string|null>
 * }
 */
final class SchemaHandle {

	/**
	 * The wrapped engine schema. Typed as `object` (rather than the engine's
	 * `Schema` class) so the class signature carries no engine-specific
	 * symbol; the inspection methods cast to engine APIs internally.
	 *
	 * @var object
	 */
	private object $engine_schema;

	/**
	 * Wrap an engine schema in a handle.
	 *
	 * @internal Reserved for dual-API infrastructure (the controller's `get_schema()` accessor and similarly placed code). Plugins obtain a handle through their own controller, not by instantiating directly.
	 *
	 * @param object $engine_schema Engine-specific schema instance the handle wraps.
	 */
	public function __construct( object $engine_schema ) {
		$this->engine_schema = $engine_schema;
	}

	/**
	 * Return every metadata row in the schema (introspection types excluded).
	 *
	 * Each row describes one *target* (a type, a field, an argument, or an
	 * enum value) and carries the name=>value entries declared on it. The
	 * same row shape is used for every target kind; the three nullable
	 * position fields (`field`, `argument`, `enumValue`) discriminate.
	 *
	 * @return list<array{type: string, field: ?string, argument: ?string, enumValue: ?string, entries: array<string, bool|int|float|string|null>}>
	 */
	public function get_all_metadata(): array {
		$rows   = array();
		$schema = $this->engine_schema;

		foreach ( $schema->getTypeMap() as $type_name => $type ) {
			if ( self::is_introspection_name( $type_name ) ) {
				continue;
			}

			$type_metadata = self::read_type_metadata( $type );
			if ( ! empty( $type_metadata ) ) {
				$rows[] = self::make_row( $type_name, null, null, null, $type_metadata );
			}

			if ( $type instanceof HasFieldsType ) {
				foreach ( $type->getFields() as $field_name => $field ) {
					$field_metadata = self::read_element_metadata( $field );
					if ( ! empty( $field_metadata ) ) {
						$rows[] = self::make_row( $type_name, $field_name, null, null, $field_metadata );
					}

					foreach ( $field->args as $arg ) {
						$arg_metadata = self::read_element_metadata( $arg );
						if ( ! empty( $arg_metadata ) ) {
							$rows[] = self::make_row( $type_name, $field_name, $arg->name, null, $arg_metadata );
						}
					}
				}
				continue;
			}

			if ( $type instanceof InputObjectType ) {
				foreach ( $type->getFields() as $field_name => $field ) {
					$field_metadata = self::read_element_metadata( $field );
					if ( ! empty( $field_metadata ) ) {
						$rows[] = self::make_row( $type_name, $field_name, null, null, $field_metadata );
					}
				}
				continue;
			}

			if ( $type instanceof EnumType ) {
				foreach ( $type->getValues() as $value ) {
					$value_metadata = self::read_element_metadata( $value );
					if ( ! empty( $value_metadata ) ) {
						$rows[] = self::make_row( $type_name, null, null, $value->name, $value_metadata );
					}
				}
			}
		}

		return $rows;
	}

	/**
	 * Filter-narrows view over {@see self::get_all_metadata()}.
	 *
	 * Each filter argument independently restricts the result set; supplying
	 * multiple composes as AND. When `$name` is supplied, the surviving rows
	 * have their `entries` trimmed to the single matching entry; so a caller
	 * asking "which elements are marked X" gets focused rows back, not the
	 * full multi-entry shape.
	 *
	 * @param ?string $name  Optional metadata name to match. When set, only rows containing this entry survive and their `entries` are trimmed to it.
	 * @param ?string $type  Optional GraphQL type name to match.
	 * @param ?string $field Optional GraphQL field name to match.
	 *
	 * @return list<array{type: string, field: ?string, argument: ?string, enumValue: ?string, entries: array<string, bool|int|float|string|null>}>
	 */
	public function find_metadata( ?string $name = null, ?string $type = null, ?string $field = null ): array {
		$rows = $this->get_all_metadata();

		$result = array();
		foreach ( $rows as $row ) {
			if ( null !== $type && $row['type'] !== $type ) {
				continue;
			}
			if ( null !== $field && $row['field'] !== $field ) {
				continue;
			}
			if ( null !== $name ) {
				if ( ! array_key_exists( $name, $row['entries'] ) ) {
					continue;
				}
				$row['entries'] = array( $name => $row['entries'][ $name ] );
			}
			$result[] = $row;
		}

		return $result;
	}

	/**
	 * Read type-level metadata from a wrapped engine type.
	 *
	 * The wrapper subclasses in `Internal/Api/Schema/` expose `get_metadata()`;
	 * non-wrapper types (e.g. the built-in scalars, the introspection types we
	 * already filtered out) don't carry metadata and contribute an empty array.
	 *
	 * @param Type $type The GraphQL type to inspect.
	 * @return array<string, bool|int|float|string|null>
	 */
	private static function read_type_metadata( Type $type ): array {
		if ( method_exists( $type, 'get_metadata' ) ) {
			$metadata = $type->get_metadata();
			return is_array( $metadata ) ? $metadata : array();
		}
		return array();
	}

	/**
	 * Read field-/arg-/enum-value-level metadata from the original config array.
	 *
	 * FieldDefinition, Argument, InputObjectField and EnumValueDefinition all
	 * preserve their construction config in a public `$config` property, so
	 * the `metadata` key emitted by ApiBuilder is reachable here without any
	 * wrapper-side plumbing.
	 *
	 * @param object $element FieldDefinition | Argument | InputObjectField | EnumValueDefinition.
	 * @return array<string, bool|int|float|string|null>
	 */
	private static function read_element_metadata( object $element ): array {
		if ( ! property_exists( $element, 'config' ) ) {
			return array();
		}
		$metadata = $element->config['metadata'] ?? array();
		return is_array( $metadata ) ? $metadata : array();
	}

	/**
	 * Build a metadata row in the standard shape.
	 *
	 * @param string                                    $type       GraphQL type name.
	 * @param ?string                                   $field      Field name when the row describes a field; null otherwise.
	 * @param ?string                                   $argument   Argument name when the row describes a field argument; null otherwise.
	 * @param ?string                                   $enum_value Enum value name when the row describes an enum value; null otherwise.
	 * @param array<string, bool|int|float|string|null> $entries    Name=>value entries to attach to the row.
	 * @return array{type: string, field: ?string, argument: ?string, enumValue: ?string, entries: array<string, bool|int|float|string|null>}
	 */
	private static function make_row( string $type, ?string $field, ?string $argument, ?string $enum_value, array $entries ): array {
		return array(
			'type'      => $type,
			'field'     => $field,
			'argument'  => $argument,
			'enumValue' => $enum_value,
			'entries'   => $entries,
		);
	}

	/**
	 * Whether a type name belongs to GraphQL's introspection system (and so should be skipped).
	 *
	 * @param string $name Type name.
	 */
	private static function is_introspection_name( string $name ): bool {
		return str_starts_with( $name, '__' );
	}
}
