<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Internal\PushNotifications\Entities;

defined( 'ABSPATH' ) || exit;

use InvalidArgumentException;

/**
 * Object representation of a push token.
 */
final class PushToken {
	const POST_TYPE = 'push_token';

	const PLATFORM_IOS     = 'ios';
	const PLATFORM_ANDROID = 'android';
	const PLATFORM_BROWSER = 'browser';

	const ORIGIN_WOOCOMMERCE_ANDROID     = 'com.woocommerce.android';
	const ORIGIN_WOOCOMMERCE_ANDROID_DEV = 'com.woocommerce.android:dev';
	const ORIGIN_WOOCOMMERCE_IOS         = 'com.automattic.woocommerce';
	const ORIGIN_WOOCOMMERCE_IOS_DEV     = 'com.automattic.woocommerce:dev';

	const PLATFORMS = array(
		self::PLATFORM_IOS,
		self::PLATFORM_ANDROID,
		self::PLATFORM_BROWSER,
	);

	const ORIGINS = array(
		self::ORIGIN_WOOCOMMERCE_ANDROID,
		self::ORIGIN_WOOCOMMERCE_ANDROID_DEV,
		self::ORIGIN_WOOCOMMERCE_IOS,
		self::ORIGIN_WOOCOMMERCE_IOS_DEV,
	);

	/**
	 * The id of the token post.
	 *
	 * @var int|null
	 */
	private ?int $id = null;

	/**
	 * The id of the user who owns the token.
	 *
	 * @var int|null
	 */
	private ?int $user_id = null;

	/**
	 * The token representing a device we can send a push notification to.
	 *
	 * @var string|null
	 */
	private ?string $token = null;

	/**
	 * The UUID of the device that generated the token.
	 *
	 * @var string|null
	 */
	private ?string $device_uuid = null;

	/**
	 * The platform the token was generated by.
	 *
	 * @var string|null
	 */
	private ?string $platform = null;

	/**
	 * The origin the token belongs to.
	 *
	 * @var string|null
	 */
	private ?string $origin = null;

	/**
	 * Sets the ID.
	 *
	 * @param int $id The id of the token post.
	 * @throws InvalidArgumentException If ID is <= 0.
	 */
	public function set_id( int $id ): void {
		if ( $id <= 0 ) {
			throw new InvalidArgumentException( 'ID must be a positive integer.' );
		}

		$this->id = $id;
	}

	/**
	 * Sets the user ID.
	 *
	 * @param int $user_id The id of the user who owns the token.
	 * @throws InvalidArgumentException If ID is <= 0.
	 */
	public function set_user_id( int $user_id ): void {
		if ( $user_id <= 0 ) {
			throw new InvalidArgumentException( 'User ID must be a positive integer.' );
		}

		$this->user_id = $user_id;
	}

	/**
	 * Sets the token.
	 *
	 * @param string $token The token representing a device we can send a push notification to.
	 * @throws InvalidArgumentException If token is empty or too long.
	 */
	public function set_token( string $token ): void {
		$token = trim( $token );

		if ( '' === $token ) {
			throw new InvalidArgumentException( 'Token cannot be empty.' );
		}

		if ( strlen( $token ) > 4096 ) {
			throw new InvalidArgumentException( 'Token is too long.' );
		}

		$this->token = $token;
	}

	/**
	 * Sets the device UUID, normalize empty (non zero) values to null.
	 *
	 * @param string|null $device_uuid The UUID of the device that generated the token.
	 */
	public function set_device_uuid( ?string $device_uuid ): void {
		if ( null !== $device_uuid ) {
			$device_uuid = trim( $device_uuid );
		}

		$this->device_uuid = ( '' === $device_uuid ) ? null : $device_uuid;
	}

	/**
	 * Sets the platform.
	 *
	 * @param string $platform The platform the token was generated by.
	 * @throws InvalidArgumentException If the platform is invalid.
	 */
	public function set_platform( string $platform ): void {
		if ( ! in_array( $platform, self::PLATFORMS, true ) ) {
			throw new InvalidArgumentException( 'Platform for PushToken is invalid.' );
		}

		$this->platform = $platform;
	}

	/**
	 * Sets the origin.
	 *
	 * @param string $origin The origin of the token, e.g. the app it came from.
	 * @throws InvalidArgumentException If the origin is invalid.
	 */
	public function set_origin( string $origin ): void {
		if ( ! in_array( $origin, self::ORIGINS, true ) ) {
			throw new InvalidArgumentException( 'Origin for PushToken is invalid.' );
		}

		$this->origin = $origin;
	}

	/**
	 * Gets the ID.
	 *
	 * @return int|null
	 */
	public function get_id(): ?int {
		return $this->id;
	}

	/**
	 * Gets the user ID.
	 *
	 * @return int|null
	 */
	public function get_user_id(): ?int {
		return $this->user_id;
	}

	/**
	 * Gets the token.
	 *
	 * @return string|null
	 */
	public function get_token(): ?string {
		return $this->token;
	}

	/**
	 * Gets the device UUID.
	 *
	 * @return string|null
	 */
	public function get_device_uuid(): ?string {
		return $this->device_uuid;
	}

	/**
	 * Gets the platform.
	 *
	 * @return string|null
	 */
	public function get_platform(): ?string {
		return $this->platform;
	}

	/**
	 * Gets the origin.
	 *
	 * @return string|null
	 */
	public function get_origin(): ?string {
		return $this->origin;
	}

	/**
	 * Determines whether this token can be created.
	 *
	 * @return bool
	 */
	public function can_be_created(): bool {
		return ! $this->get_id()
			&& $this->get_user_id()
			&& $this->get_token()
			&& $this->get_platform()
			&& $this->get_origin()
			&& (
				$this->get_device_uuid()
				|| $this->get_platform() === self::PLATFORM_BROWSER
			);
	}

	/**
	 * Determines whether this token can be updated.
	 *
	 * @return bool
	 */
	public function can_be_updated(): bool {
		return $this->get_id()
			&& $this->get_user_id()
			&& $this->get_token()
			&& $this->get_platform()
			&& $this->get_origin()
			&& (
				$this->get_device_uuid()
				|| $this->get_platform() === self::PLATFORM_BROWSER
			);
	}

	/**
	 * Determines whether this token can be read.
	 *
	 * @return bool
	 */
	public function can_be_read(): bool {
		return (bool) $this->get_id();
	}

	/**
	 * Determines whether this token can be deleted.
	 *
	 * @return bool
	 */
	public function can_be_deleted(): bool {
		return (bool) $this->get_id();
	}
}
