/** @format */

export default [
	{
		product_id: 658,
		items_sold: 8,
		gross_revenue: 6625.76,
		orders_count: 1,
		name: 'Mug',
		stock_quantity: 184,
		categories: [],
		variations: [],
	},
	{
		product_id: 412,
		items_sold: 4,
		gross_revenue: 60,
		orders_count: 1,
		name: 'Beanie',
		stock_quantity: 98,
		categories: [],
		variations: [],
	},
	{
		product_id: 724,
		items_sold: 11,
		gross_revenue: 6552.37,
		orders_count: 2,
		name: 'Sweater',
		stock_quantity: null,
		categories: [],
		variations: [],
	},
	{
		product_id: 653,
		items_sold: 14,
		gross_revenue: 2566.76,
		orders_count: 2,
		name: 'Octopus Tee',
		stock_quantity: 114,
		categories: [],
		variations: [],
	},
	{
		product_id: 254,
		items_sold: 9,
		gross_revenue: 135,
		orders_count: 1,
		name: 'Bubble Tee',
		stock_quantity: 79,
		categories: [],
		variations: [ 255, 256, 257 ],
	},
];
