<?php

declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Pagination;

use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\WidgetReview as WidgetReviewType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class WidgetReviewEdge {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'   => 'WidgetReviewEdge',
					'fields' => fn() => array(
						'cursor' => array(
							'type' => Type::nonNull( Type::string() ),
						),
						'node'   => array(
							'type' => Type::nonNull( WidgetReviewType::get() ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
