<?php
/**
 * Loads the experimental payment settings screen.
 */

declare( strict_types=1 );

namespace Automattic\WooCommerce\Internal\Admin\Settings;

use Automattic\WooCommerce\Admin\Features\Features;

defined( 'ABSPATH' ) || exit;

/**
 * Registers the wp-build admin page for payment gateway settings screens.
 *
 * This class is the only code that loads the build output in
 * `assets/client/routes`, which defines wp-build's generated functions.
 *
 * @internal
 */
class PaymentSettingsScreen {

	/**
	 * Admin page slug. wp-build's generated code only loads its assets on this page.
	 */
	public const PAGE_SLUG = 'wc-payment-settings-wp-admin';

	/**
	 * Feature flag that controls the screen until it is released.
	 */
	private const FEATURE_FLAG = 'payment-settings-screen';

	/**
	 * Name of the render function generated by wp-build.
	 */
	private const RENDER_FUNCTION = 'woocommerce_routes_wc_payment_settings_wp_admin_render_page';

	/**
	 * Handle of the script that passes the current screen to the route.
	 */
	private const DATA_SCRIPT_HANDLE = 'wc-payment-settings-screen';

	/**
	 * The registered screens.
	 *
	 * @var PaymentSettingsScreens
	 */
	private PaymentSettingsScreens $screens;

	/**
	 * Register hooks.
	 */
	public function __construct() {
		add_action( 'init', array( $this, 'handle_init' ) );
	}

	/**
	 * Initialize dependencies.
	 *
	 * @internal
	 *
	 * @param PaymentSettingsScreens $screens The registered screens.
	 */
	final public function init( PaymentSettingsScreens $screens ): void {
		$this->screens = $screens;
	}

	/**
	 * Load the generated page when the screen is available.
	 *
	 * @internal
	 */
	public function handle_init(): void {
		if ( ! is_admin() || is_network_admin() || ! $this->is_available() ) {
			return;
		}

		require_once $this->get_build_file();
		add_action( 'admin_menu', array( $this, 'handle_admin_menu' ) );
		add_action( 'admin_head', array( $this, 'handle_admin_head' ) );
		add_filter( 'submenu_file', array( $this, 'handle_submenu_file' ) );
		add_action( 'wc-payment-settings-wp-admin_init', array( $this, 'handle_page_init' ) );
	}

	/**
	 * Load the requested screen's scripts and pass its settings to the route.
	 *
	 * @internal
	 */
	public function handle_page_init(): void {
		$screen = $this->get_requested_screen();
		if ( null === $screen ) {
			return;
		}

		foreach ( $screen['scripts'] as $handle ) {
			wp_enqueue_script( $handle );
		}

		$module_dependencies = array_map(
			static fn( string $module_id ) => array(
				'id'      => $module_id,
				'dynamic' => true,
			),
			$this->get_field_module_ids( $screen['id'] )
		);

		// Registered without a source: it only carries the screen data and the field modules for the import map.
		wp_register_script(
			self::DATA_SCRIPT_HANDLE,
			false,
			array(),
			WC_VERSION,
			array(
				'in_footer'           => true,
				'module_dependencies' => $module_dependencies,
			)
		);
		wp_add_inline_script(
			self::DATA_SCRIPT_HANDLE,
			'window.wcPaymentSettingsScreen = ' . wp_json_encode(
				array(
					'id'     => $screen['id'],
					'title'  => $screen['title'],
					'entity' => array(
						'kind'    => PaymentSettingsScreens::ENTITY_KIND,
						'name'    => $screen['id'],
						'baseURL' => $screen['rest_path'],
					),
				)
			) . ';',
			'before'
		);
		wp_enqueue_script( self::DATA_SCRIPT_HANDLE );
	}

	/**
	 * Whether the screen can be used on this site.
	 *
	 * It needs the feature flag, WordPress's View Config and Fields APIs, and the build output.
	 *
	 * @since 11.4.0
	 *
	 * @return bool
	 */
	public function is_available(): bool {
		return Features::is_enabled( self::FEATURE_FLAG )
			&& function_exists( 'wp_get_entity_view_config' )
			&& ( class_exists( 'WP_Fields_Registry' ) || class_exists( 'Gutenberg_Fields_Registry' ) )
			&& is_readable( $this->get_build_file() );
	}

	/**
	 * Register the page under WooCommerce so the menu opens on it.
	 *
	 * @internal
	 */
	public function handle_admin_menu(): void {
		if ( ! function_exists( self::RENDER_FUNCTION ) ) {
			return;
		}

		add_submenu_page(
			'woocommerce',
			__( 'Payment settings', 'woocommerce' ),
			__( 'Payment settings', 'woocommerce' ),
			'manage_woocommerce',
			self::PAGE_SLUG,
			array( $this, 'render_page' )
		);
	}

	/**
	 * Render the page through wp-build's generated function.
	 *
	 * @internal
	 */
	public function render_page(): void {
		if ( function_exists( self::RENDER_FUNCTION ) ) {
			// @phpstan-ignore argument.type (wp-build generates this function in the build output, which PHPStan does not load.)
			call_user_func( self::RENDER_FUNCTION );
		}
	}

	/**
	 * Remove the page's own menu item; gateways link to the screen directly.
	 *
	 * Removing it after the menu is built keeps WooCommerce as the page's parent.
	 *
	 * @internal
	 */
	public function handle_admin_head(): void {
		remove_submenu_page( 'woocommerce', self::PAGE_SLUG );
	}

	/**
	 * Highlight WooCommerce > Settings on the screen.
	 *
	 * @internal
	 *
	 * @param mixed $submenu_file The submenu file.
	 * @return mixed
	 */
	public function handle_submenu_file( $submenu_file ) {
		return $this->is_current_page() ? 'wc-settings' : $submenu_file;
	}

	/**
	 * Whether the current admin request is for the screen.
	 *
	 * @return bool
	 */
	private function is_current_page(): bool {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Only compares the page slug.
		return isset( $_GET['page'] ) && self::PAGE_SLUG === $_GET['page'];
	}

	/**
	 * Get the screen named in the route, such as `p=/settings/woopayments`.
	 *
	 * @return array{id: string, title: string, rest_path: string, scripts: string[]}|null
	 */
	private function get_requested_screen(): ?array {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Only selects which screen to load.
		$route = isset( $_GET['p'] ) && is_string( $_GET['p'] ) ? sanitize_text_field( wp_unslash( $_GET['p'] ) ) : '';
		if ( ! preg_match( '#^/settings/([a-z0-9_-]+)/?(?:\?.*)?$#', $route, $matches ) ) {
			return null;
		}

		return $this->screens->get_screen( $matches[1] );
	}

	/**
	 * Get the script modules registered with the Fields API for a screen's entity.
	 *
	 * @param string $screen_id The screen ID.
	 * @return string[]
	 */
	private function get_field_module_ids( string $screen_id ): array {
		if ( function_exists( 'wp_get_registered_field_modules' ) ) {
			$modules = wp_get_registered_field_modules( PaymentSettingsScreens::ENTITY_KIND, $screen_id );
		} elseif ( function_exists( 'gutenberg_get_registered_field_modules' ) ) {
			$modules = gutenberg_get_registered_field_modules( PaymentSettingsScreens::ENTITY_KIND, $screen_id );
		} else {
			return array();
		}

		return is_array( $modules ) ? array_values( array_filter( array_keys( $modules ), 'is_string' ) ) : array();
	}

	/**
	 * Path to the wp-build entry point.
	 *
	 * @return string
	 */
	private function get_build_file(): string {
		return WC_ABSPATH . 'assets/client/routes/build.php';
	}
}
