#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

recommend_nvm=true
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
if command -v nvm >/dev/null 2>&1 && [ -f .nvmrc ]; then
	recommend_nvm=false
	nvm install
fi

pnpm install

if [ "$recommend_nvm" = true ]; then
	echo "Could not find nvm; installation is recommended."
fi
