name: 'Release: Update stable tag'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (in X.Y or X.Y.Z format)'
        required: true
        default: ''

jobs:
  update-wporg-stable-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate release version
        id: extract-version
        uses: actions/github-script@v7
        with:
          script: |
            const versionInput = '${{ github.event.inputs.version }}';
            const versionMatch = versionInput.match(/^(\d+\.\d+\.\d+(?:-[a-z]+)?)$/);
            if (versionMatch) {
              const version = versionMatch[1];
              console.log(`Extracted version: ${version}`);
              core.setOutput('version', version);
            } else {
              core.setFailed(`Version ${versionInput} does not match the expected format (X.Y.Z or X.Y.Z-tag)`);
              process.exit(1);
            }
