name: Storybook GitHub Pages

on:
    schedule:
        - cron: '30 2 * * *'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'woocommerce/woocommerce' }}

        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  ref: trunk
                  fetch-depth: 0

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  install: '@woocommerce/storybook...'

            - name: Build Storybook
              run: pnpm --filter='@woocommerce/storybook' build
              env:
                  STORYBOOK_COMPOSITION_PATH_PREFIX: /woocommerce

            - name: Deploy
              uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./tools/storybook/storybook-static
                  force_orphan: true

            - name: Report failure on Slack
              if: ${{ failure() }}
              env:
                  SLACK_TOKEN: ${{ secrets.E2E_SLACK_TOKEN }}
                  DEFAULT_CHECKS_CHANNEL: ${{ secrets.TEST_REPORTS_SLACK_CHANNEL }}
                  DAILY_CHECKS_CHANNEL: ${{ secrets.DAILY_CHECKS_CHANNEL }}
              run: pnpm utils slack-test-report -c failure -r "nightly-checks Storybook build and deploy" --config ".github/workflows/slack-report-config.json"
