name: 'Daily tests run'
on:
  schedule:
    - cron: '25 3 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run tests'
    if: github.repository == 'woocommerce/woocommerce'
    uses: ./.github/workflows/ci.yml
    with:
      trigger: 'daily-checks'
    secrets: inherit
