name: 'Update contributor feedback labels on comment'
on: 'issue_comment'

permissions: {}

jobs:
  feedback:
    if: |
      github.actor != 'github-actions' &&
      github.actor == github.event.issue.user.login &&
      github.event.issue &&
      github.event.issue.state == 'open' &&
      contains(github.event.issue.labels.*.name, 'needs: author feedback')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write
    steps:
    - name: Check out the composite action
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        sparse-checkout: .github/actions
    - name: Swap author feedback labels for triage feedback
      uses: ./.github/actions/manage-labels
      with:
        add: 'needs: triage feedback'
        remove: |
          needs: author feedback
          status: stale
