/**
 * External dependencies
 */
import { __ } from '@wordpress/i18n';
import { WC_BLOCKS_IMAGE_URL } from '@woocommerce/block-settings';
import { ProductResponseItem } from '@woocommerce/types';

export const previewProductResponseItems: ProductResponseItem[] = [
	{
		id: 1,
		name: __( 'Beanie', 'woocommerce' ),
		parent: 0,
		type: 'simple',
		variation: '',
		permalink: 'https://example.org',
		slug: 'wp-beanie',
		sku: 'wp-beanie',
		short_description: __( 'Warm hat for winter', 'woocommerce' ),
		description:
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.',
		price: '799',
		price_html:
			'<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>7.99</span>',
		images: [
			{
				id: 1,
				src: WC_BLOCKS_IMAGE_URL + 'previews/beanie.jpg',
				thumbnail: WC_BLOCKS_IMAGE_URL + 'previews/beanie.jpg',
				name: 'beanie-1.jpg',
				alt: 'Beanie',
				srcset: '',
				sizes: '',
			},
		],
		average_rating: '5',
		categories: [
			{
				id: 1,
				name: 'Clothing',
				slug: 'clothing',
				link: 'https://example.org',
			},
		],
		tags: [],
		attributes: [],
		variations: [],
		review_count: 1,
		prices: {
			currency_code: 'USD',
			currency_symbol: '$',
			currency_minor_unit: 2,
			currency_decimal_separator: '.',
			currency_thousand_separator: ',',
			currency_prefix: '$',
			currency_suffix: '',
			price: '799',
			regular_price: '999',
			sale_price: '799',
			price_range: null,
		},
		add_to_cart: {
			text: __( 'Add to cart', 'woocommerce' ),
			description: __( 'Add to cart', 'woocommerce' ),
			url: '#',
			minimum: 1,
			maximum: 9999,
			multiple_of: 1,
			single_text: __( 'Add to cart', 'woocommerce' ),
		},
		has_options: false,
		is_purchasable: true,
		is_in_stock: true,
		is_on_backorder: false,
		low_stock_remaining: null,
		stock_availability: {
			text: __( 'In stock', 'woocommerce' ),
			class: 'in-stock',
		},
		sold_individually: false,
		grouped_products: [],
		regular_price: '999',
		sale_price: '799',
		on_sale: true,
	},
	{
		id: 2,
		name: __( 'Cap', 'woocommerce' ),
		parent: 0,
		type: 'simple',
		variation: '',
		permalink: 'https://example.org',
		slug: 'wp-cap',
		sku: 'wp-cap',
		short_description: __( 'Warm hat for winter', 'woocommerce' ),
		description:
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.',
		price: '2299',
		price_html:
			'<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>22.99</span>',
		images: [
			{
				id: 1,
				src: WC_BLOCKS_IMAGE_URL + 'previews/cap.jpg',
				thumbnail: WC_BLOCKS_IMAGE_URL + 'previews/cap.jpg',
				name: 'cap-1.jpg',
				alt: 'Cap',
				srcset: '',
				sizes: '',
			},
		],
		average_rating: '5',
		categories: [
			{
				id: 1,
				name: 'Clothing',
				slug: 'clothing',
				link: 'https://example.org',
			},
		],
		tags: [],
		attributes: [],
		variations: [],
		review_count: 1,
		prices: {
			currency_code: 'USD',
			currency_symbol: '$',
			currency_minor_unit: 2,
			currency_decimal_separator: '.',
			currency_thousand_separator: ',',
			currency_prefix: '$',
			currency_suffix: '',
			price: '2299',
			regular_price: '2499',
			sale_price: '2299',
			price_range: null,
		},
		add_to_cart: {
			text: __( 'Add to cart', 'woocommerce' ),
			description: __( 'Add to cart', 'woocommerce' ),
			url: '#',
			minimum: 1,
			maximum: 9999,
			multiple_of: 1,
			single_text: __( 'Add to cart', 'woocommerce' ),
		},
		has_options: false,
		is_purchasable: true,
		is_in_stock: true,
		is_on_backorder: false,
		low_stock_remaining: null,
		stock_availability: {
			text: __( 'In stock', 'woocommerce' ),
			class: 'in-stock',
		},
		sold_individually: false,
		grouped_products: [],
		regular_price: '2499',
		sale_price: '2299',
		on_sale: true,
	},
	{
		id: 3,
		name: __( 'Polo', 'woocommerce' ),
		parent: 0,
		type: 'simple',
		variation: '',
		permalink: 'https://example.org',
		slug: 'polo',
		sku: 'woo-polo',
		short_description: __( 'Polo', 'woocommerce' ),
		description: 'Polo',
		price: '2299',
		price_html:
			'<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>22.99</span>',
		images: [
			{
				id: 1,
				src: WC_BLOCKS_IMAGE_URL + 'previews/polo.jpg',
				thumbnail: WC_BLOCKS_IMAGE_URL + 'previews/polo.jpg',
				name: 'polo-1.jpg',
				alt: 'Polo',
				srcset: '',
				sizes: '',
			},
		],
		average_rating: '5',
		categories: [
			{
				id: 1,
				name: 'Clothing',
				slug: 'clothing',
				link: 'https://example.org',
			},
		],
		tags: [],
		attributes: [],
		variations: [],
		review_count: 1,
		prices: {
			currency_code: 'USD',
			currency_symbol: '$',
			currency_minor_unit: 2,
			currency_decimal_separator: '.',
			currency_thousand_separator: ',',
			currency_prefix: '$',
			currency_suffix: '',
			price: '2299',
			regular_price: '2499',
			sale_price: '2299',
			price_range: null,
		},
		add_to_cart: {
			text: __( 'Add to cart', 'woocommerce' ),
			description: __( 'Add to cart', 'woocommerce' ),
			url: '#',
			minimum: 1,
			maximum: 9999,
			multiple_of: 1,
			single_text: __( 'Add to cart', 'woocommerce' ),
		},
		has_options: false,
		is_purchasable: true,
		is_in_stock: true,
		is_on_backorder: false,
		low_stock_remaining: null,
		stock_availability: {
			text: __( 'In stock', 'woocommerce' ),
			class: 'in-stock',
		},
		sold_individually: false,
		grouped_products: [],
		regular_price: '2499',
		sale_price: '2299',
		on_sale: true,
	},
];
